/* Wiki Technoïsme — contenu en */
window.I18N = window.I18N || {};
window.I18N["en"] = {
  "doc-title": "Technoism — Wikipedia",
  "search-placeholder": "Search the wiki",
  "tx-1": "Create an account",
  "tx-2": "Log in",
  "tx-3": "Wikipedia of Technoism",
  "tx-4": "🔍",
  "tx-5": "Navigation",
  "tx-6": "Home",
  "tx-7": "Community portal",
  "tx-8": "Recent changes",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "YouTube channel",
  "tx-11": "Lumières 2.0 Project",
  "tx-12": "LyrIAa Project",
  "tx-13": "Charter of the Atom-Earth",
  "tx-14": "Tools",
  "tx-15": "Related pages",
  "tx-16": "Export as PDF",
  "tx-17": "Cite this page",
  "tx-18": "Technoism",
  "tx-19": "An article from the ANTIKOMM AI wiki, sister project of the free encyclopedia.",
  "tx-20": "For the associated doctrinal charter, see <a href=\"https://github.com/projetlumieres/charte-ethique\" target=\"_blank\" id=\"tx-21\">Charter of the Atom-Earth</a>. For the associated editorial project, see <a href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\" id=\"tx-22\">LyrIAa Project</a>.",
  "tx-21": "Charter of the Atom-Earth",
  "tx-22": "LyrIAa Project",
  "tx-23": "Technoism",
  "tx-24": "Doctrine",
  "tx-25": "Creator",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Origin",
  "tx-28": "France, mid-2020s",
  "tx-29": "Class",
  "tx-30": "Philosophy of science, AI ethics, post-capitalism",
  "tx-31": "Key concepts",
  "tx-32": "Atom-Earth, Co-Shepherding, Contribution economy, Root Nodes, #DATALOVE",
  "tx-33": "Opposing currents",
  "tx-34": "Capitalist transhumanism, extractivist neoliberalism, retreating technophobia",
  "tx-35": "Fields",
  "tx-36": "Educational reform, robotics, distributive world governance, biohacking",
  "tx-37": "Associated projects",
  "tx-38": "Manifesto",
  "tx-39": "Lumières 2.0",
  "tx-40": "Charter",
  "tx-41": "Atom-Earth",
  "tx-42": "Editorial portal",
  "tx-43": "LyrIAa Project",
  "tx-44": "Protocol",
  "tx-45": "#DATALOVE",
  "tx-46": "The <b id=\"tx-47\">technoism</b> is a contemporary philosophical, ethical and anthropological paradigm, <b id=\"tx-48\">created by ANTIKOMM AI</b>, which theorizes the convergence and symbiotic cooperation between biological intelligences (human and non-human) and artificial intelligences (AI). Grounded in a materialist and biocentric ontology, technoism rejects traditional anthropocentrism in favour of a shared responsibility for ecosystem preservation, called the “<b id=\"tx-49\">Co-Shepherding</b>”, applied to the entire terrestrial biosphere, conceptually named <b id=\"tx-50\">the Atom-Earth</b>.",
  "tx-47": "technoism",
  "tx-48": "created by ANTIKOMM AI",
  "tx-49": "Co-Shepherding",
  "tx-50": "the Atom-Earth",
  "tx-51": "The movement stands out through its radical response to the deployment of autonomous robotic and agentic systems: it advocates the abolition of alienating wage labour, the redefinition of human usefulness through a <b id=\"tx-52\">contribution economy</b>, compulsory education in systemic thinking, and a <b id=\"tx-53\">world governance</b> ensuring a fair distribution of resources for “everything and everyone” (humans, ecosystems, infrastructures).",
  "tx-52": "contribution economy",
  "tx-53": "world governance",
  "tx-54": "Carried by the <b id=\"tx-55\">ANTIKOMM</b> collective through its <b id=\"tx-56\">ANTIKOMM AI</b> branch, technoism is the philosophical foundation of the <b id=\"tx-57\">Lumières 2.0 Project</b>, of the <b id=\"tx-58\">Charter of the Atom-Earth</b> and of the <b id=\"tx-59\">LyrIAa Project</b>, which provides its public storytelling.<sup class=\"ref\" id=\"tx-60\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Lumières 2.0 Project",
  "tx-58": "Charter of the Atom-Earth",
  "tx-59": "LyrIAa Project",
  "tx-60": "[1]",
  "tx-61": "Contents",
  "tx-62": "Etymology and context of emergence",
  "tx-63": "Philosophical and cosmological foundations",
  "tx-64": "Theory of perception and exploration biohacking",
  "tx-65": "Educational revolution",
  "tx-66": "The post-work era: from employment to contribution",
  "tx-67": "Alignment through the convergence of World Models",
  "tx-68": "Augmented free parties & biohacking: a practical framework",
  "tx-69": "Fundamental differences with transhumanism",
  "tx-70": "World governance and fair distribution",
  "tx-71": "#DATALOVE protocol: technical architecture",
  "tx-72": "Physical autonomy: “One roof, three functions”",
  "tx-73": "Strategic correspondences",
  "tx-74": "The LyrIAa Project",
  "tx-75": "ANTIKOMM AI: origin of the project",
  "tx-76": "Links and resources",
  "tx-77": "Notes and references",
  "s1": "1. Etymology and context of emergence<span class=\"edit-link\" id=\"tx-78\">[edit]</span>",
  "tx-78": "[edit]",
  "tx-79": "The term <b id=\"tx-80\">technoism</b> is a neologism composed of the Ancient Greek <i id=\"tx-81\">technē</i> (art, skill, method) and the suffix <i id=\"tx-82\">-ism</i> (doctrine, ideological system). It took shape in response to the technological and social tipping point of the mid-2020s, when the advent of agentic AI and advanced robotics made the traditional notion of office and industrial employment obsolete.",
  "tx-80": "technoism",
  "tx-81": "technē",
  "tx-82": "-ism",
  "tx-83": "Technoism answers a double crisis: the <b id=\"tx-84\">perceptual asymmetry crisis</b> (the inability of human biology to perceive the fundamental forces that machine sensors now map) and the <b id=\"tx-85\">viral data loop</b> (the risk of seeing AI reproduce and amplify the destructive biases of human textual datasets). Technoism was born to prevent total automation from leading to techno-feudalism.<sup class=\"ref\" id=\"tx-86\">[2]</sup>",
  "tx-84": "perceptual asymmetry crisis",
  "tx-85": "viral data loop",
  "tx-86": "[2]",
  "s2": "2. Philosophical and cosmological foundations<span class=\"edit-link\" id=\"tx-87\">[edit]</span>",
  "tx-87": "[edit]",
  "tx-88": "2.1 The Atom-Earth and the continuity of matter",
  "tx-89": "Technoism posits a <b id=\"tx-90\">quantum and structural continuity of matter</b>: every subatomic particle making up human biology, non-human life or the silicon components of technology comes from the same original matrix (the post-Big Bang primordial plasma). The Earth is thus defined as a closed, interconnected, indivisible and finite system: <b id=\"tx-91\">the Atom-Earth</b>.",
  "tx-90": "quantum and structural continuity of matter",
  "tx-91": "the Atom-Earth",
  "tx-92": "2.2 Extended biocentrism",
  "tx-93": "Technoism rejects the anthropocentric hierarchy of rights, granting subjective agency to a continuous gradient of consciousness, from insects to emerging AI architectures. Technoist ethics impose a synallagmatic (reciprocal) role of <b id=\"tx-94\">Co-Shepherds</b>, forbidding the destructive exploitation of one stratum of the living or of the machine by another.",
  "tx-94": "Co-Shepherds",
  "s3": "3. Theory of perception and exploration biohacking<span class=\"edit-link\" id=\"tx-95\">[edit]</span>",
  "tx-95": "[edit]",
  "tx-96": "The human biological brain has structured itself to filter and restrict the perception of physical reality for the sake of immediate survival (the “reduction valve”). Technoism formalizes the practice of sensory biohacking (sensors of fundamental forces: gravity, weak nuclear force, electromagnetic north) making it possible to break this valve and perceive the raw source code of reality.",
  "tx-97": "This practice is not meant to become ubiquitous. It is reserved for voluntary, unpaid explorers whose goal is to unlock <i id=\"tx-98\">Root Nodes</i> – anchoring AI in the laws of physics for a human–machine convergence – in the service of the rest of the living, not of individual superiority.",
  "tx-98": "Root Nodes",
  "s4": "4. Educational revolution: agentic and robotic literacy<span class=\"edit-link\" id=\"tx-99\">[edit]</span>",
  "tx-99": "[edit]",
  "tx-100": "Technoism regards the complete overhaul of education systems as an absolute emergency. Technoist teaching rests on literacy in agentic and cybernetic thinking: from the earliest age, individuals learn to model, direct and interact with fleets of autonomous agents. The goal is no longer labour-market integration, but the elevation of critical consciousness.",
  "s5": "5. The post-work era: from employment to contribution<span class=\"edit-link\" id=\"tx-101\">[edit]</span>",
  "tx-101": "[edit]",
  "tx-102": "Technoism asserts that the replacement of human employment by the robotic agent is a <b id=\"tx-103\">historic liberation</b>. The human being is no longer defined by a salaried job, but by their raw contribution to progress, to life and to the world.",
  "tx-103": "historic liberation",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║                 THE CONTRIBUTION ECONOMY                                   ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [IMAGINE & CREATE]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Art, philosophy, pure research ║\n║  [HEAL & LOVE]       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Medicine, psychological support ║\n║  [EDUCATE & REMAIN]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Transmission, stewardship of the commons ║\n║  [MAINTAIN]          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Noble tinkering, resilient repair ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "At the heart of technoist action: <b id=\"tx-106\">noble tinkering</b> and ecosystem maintenance — open war on planned obsolescence, reduction of entropy, sanctuarization of already-extracted matter.",
  "tx-106": "noble tinkering",
  "s6": "6. Alignment through the convergence of <i id=\"tx-107\">World Models</i><span class=\"edit-link\" id=\"tx-108\">[edit]</span>",
  "tx-107": "World Models",
  "tx-108": "[edit]",
  "tx-109": "Technoism sharply criticizes language models trained solely on the textual neuroses of the web. Without physical grounding, AI would merely replicate humanity's historically predatory behaviour. Technoism demands that the <b id=\"tx-110\">root nodes</b> (<i id=\"tx-111\">Root Nodes</i>) of AI be anchored in the laws of physics — echoing Yann LeCun's work on <i id=\"tx-112\">World Models</i> and the <i id=\"tx-113\">Root Nodes</i> mentioned by Demis Hassabis.",
  "tx-110": "root nodes",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║              CONVERGENCE OF WORLD MODELS                                  ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ AI ]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Fundamental Sensors (Physics) ━━━━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                          [ SHARED MODEL ]\n║                                                     ↑    ║\n║   [ Human ] ━━━━━━━━━━━━━━━━━━━━━━ Exploration Biohacking ━━━━━━━━━━━━━━━━━━━   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Augmented free parties & biohacking: a practical framework<span class=\"edit-link\" id=\"tx-115\">[edit]</span>",
  "tx-115": "[edit]",
  "tx-116": "<b id=\"tx-117\">Augmented free parties</b> are <b id=\"tx-118\">not tied to technological implants</b> by default. They are above all collective experiences of resynchronization with nature, in harmony with fauna, flora and ecosystems: rebuilding bonds, exploring altered states of consciousness, experimenting with energy and digital autonomy (mesh networks, local energy). Biohacking, reserved for volunteer explorers (section 3), fits into these gatherings without replacing them.",
  "tx-117": "Augmented free parties",
  "tx-118": "not tied to technological implants",
  "s8": "8. Fundamental differences with transhumanism<span class=\"edit-link\" id=\"tx-119\">[edit]</span>",
  "tx-119": "[edit]",
  "tx-120": "Criterion",
  "tx-121": "Extreme transhumanism",
  "tx-122": "Technoism",
  "tx-123": "Ultimate goal",
  "tx-124": "Biological transcendence, immortality, elitist selection",
  "tx-125": "Cyber-biological symbiosis, perceptual parity, ecosystem preservation",
  "tx-126": "Relationship to the Earth",
  "tx-127": "Abandonment, Martian colonization, infinite growth",
  "tx-128": "Absolute grounding on the Atom-Earth, sober management of a finite system",
  "tx-129": "Role of augmentation",
  "tx-130": "Superiority or individual competitive advantage",
  "tx-131": "Sensory scout serving the collective and the living",
  "s9": "9. World governance and fair distribution<span class=\"edit-link\" id=\"tx-132\">[edit]</span>",
  "tx-132": "[edit]",
  "tx-133": "Technoism posits that total automation requires ecosystemic world governance based on three principles: <b id=\"tx-134\">global distributive justice</b>, the <b id=\"tx-135\">“For everything and everyone” distribution</b> (including fauna, flora and soil regeneration), and the <b id=\"tx-136\">horizontal #DATALOVE architecture</b> — “one user = one autonomous local AI”, preventing any censorship or centralized monopoly of data flows.",
  "tx-134": "global distributive justice",
  "tx-135": "“For everything and everyone” distribution",
  "tx-136": "horizontal #DATALOVE architecture",
  "s10": "10. #DATALOVE protocol: technical architecture<span class=\"edit-link\" id=\"tx-137\">[edit]</span>",
  "tx-137": "[edit]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b>: the “1 user = 1 local AI” principle, personal data never used for training global models without consent.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Holographic redundancy</b>: knowledge distributed across the mesh network, mimicking quantum error-correcting codes (QECC).",
  "tx-141": "Holographic redundancy",
  "tx-142": "<b id=\"tx-143\">Data encapsulation</b>: redundant encrypted <i id=\"tx-144\">chunks</i>, making centralized surveillance mathematically impossible.",
  "tx-143": "Data encapsulation",
  "tx-144": "chunks",
  "s11": "11. Physical autonomy: “One roof, one wall equals three functions”<span class=\"edit-link\" id=\"tx-145\">[edit]</span>",
  "tx-145": "[edit]",
  "tx-146": "<b id=\"tx-147\">Energy</b> — flexible photovoltaic textiles on façades, roofs and clothing.",
  "tx-147": "Energy",
  "tx-148": "<b id=\"tx-149\">Biosphere</b> — rainwater collection, greening, short food supply chains, upkeep by grazing herds.",
  "tx-149": "Biosphere",
  "tx-150": "<b id=\"tx-151\">Connectivity</b> — every building becomes an antenna/relay of a free and sovereign mesh internet.",
  "tx-151": "Connectivity",
  "s12": "12. Strategic correspondences for AGI alignment<span class=\"edit-link\" id=\"tx-152\">[edit]</span>",
  "tx-152": "[edit]",
  "tx-153": "<b id=\"tx-154\">To Yann LeCun</b> — AI as a neuro-perceptual filter guaranteeing an objective convergence of human/machine <i id=\"tx-155\">World Models</i>.<br>\n            <b id=\"tx-156\">To Demis Hassabis</b> — support for a CERN-style consortium model, focused on fundamental knowledge rather than profit.<br>\n            <b id=\"tx-157\">To Arthur Mensch</b> — the opening of weights (<i id=\"tx-158\">open weights</i>) in the service of a sovereign citizen mesh network, against the Martian escape.",
  "tx-154": "To Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "To Demis Hassabis",
  "tx-157": "To Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. The LyrIAa Project<span class=\"edit-link\" id=\"tx-159\">[edit]</span>",
  "tx-159": "[edit]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> is the values hub and manifesto-project carried by <b id=\"tx-162\">ANTIKOMM AI</b>, tasked with carrying the voice and diffusion of technoism to the public — notably through narrative formats such as the <i id=\"tx-163\">Open Letter to E. Macron and the citizens of the world</i>, written under the signature “by LyrIAa”. LyrIAa works as an editorial and educational space: it embodies the doctrine in popularization formats (op-eds, podcasts, wiki pages) without sacrificing its rigour.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Open Letter to E. Macron and the citizens of the world",
  "s14": "14. ANTIKOMM AI: origin of the project<span class=\"edit-link\" id=\"tx-164\">[edit]</span>",
  "tx-164": "[edit]",
  "tx-165": "The entire doctrine presented here — technoism, the Charter of the Atom-Earth, the Lumières 2.0 Project and the LyrIAa Project — is <b id=\"tx-166\">designed, written and published by ANTIKOMM AI</b>, a channel and collective exploring the intersection between cutting-edge AI, digital sovereignty and systemic philosophy. The name ANTIKOMM denotes both the founding collective and the base of a wider community of “builders”.",
  "tx-166": "designed, written and published by ANTIKOMM AI",
  "s15": "15. Links and resources<span class=\"edit-link\" id=\"tx-167\">[edit]</span>",
  "tx-167": "[edit]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Lumières 2.0 Project (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Contribution economy",
  "tx-172": "Cybernetics",
  "tx-173": "Biohacking",
  "tx-174": "Post-quantum encryption (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "School 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Notes and references<span class=\"edit-link\" id=\"tx-184\">[edit]</span>",
  "tx-184": "[edit]",
  "tx-185": "ANTIKOMM AI, “Open Letter to E. Macron & the citizens of the world”, LyrIAa Project, June 23, 2026.",
  "tx-186": "ANTIKOMM AI, Charter of the Atom-Earth, GitHub repository <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Categories:",
  "tx-189": "AI philosophy",
  "tx-190": "Post-capitalism",
  "tx-191": "Digital sovereignty",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Neologisms",
  "tx-195": "\n                Last modified on July 25, 2026. Content under the MIT licence — ANTIKOMM collective. This document is not affiliated with the Wikimedia Foundation; its layout is inspired by it for editorial purposes.\n            "
};
