/* Wiki Technoïsme — contenu es */
window.I18N = window.I18N || {};
window.I18N["es"] = {
  "doc-title": "Tecnoísmo — Wikipedia",
  "search-placeholder": "Buscar en el wiki",
  "tx-1": "Crear una cuenta",
  "tx-2": "Iniciar sesión",
  "tx-3": "Wikipedia del Tecnoísmo",
  "tx-4": "🔍",
  "tx-5": "Navegación",
  "tx-6": "Portada",
  "tx-7": "Portal comunitario",
  "tx-8": "Cambios recientes",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "Canal de YouTube",
  "tx-11": "Proyecto Lumières 2.0",
  "tx-12": "Proyecto LyrIAa",
  "tx-13": "Carta del Átomo-Tierra",
  "tx-14": "Herramientas",
  "tx-15": "Páginas vinculadas",
  "tx-16": "Exportar a PDF",
  "tx-17": "Citar esta página",
  "tx-18": "Tecnoísmo",
  "tx-19": "Un artículo del wiki de ANTIKOMM AI, proyecto hermano de la enciclopedia libre.",
  "tx-20": "Para la carta doctrinal asociada, véase <a href=\"https://github.com/projetlumieres/charte-ethique\" target=\"_blank\" id=\"tx-21\">Carta del Átomo-Tierra</a>. Para el proyecto editorial asociado, véase <a href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\" id=\"tx-22\">Proyecto LyrIAa</a>.",
  "tx-21": "Carta del Átomo-Tierra",
  "tx-22": "Proyecto LyrIAa",
  "tx-23": "Tecnoísmo",
  "tx-24": "Doctrina",
  "tx-25": "Creador",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Origen",
  "tx-28": "Francia, mediados de los años 2020",
  "tx-29": "Clase",
  "tx-30": "Filosofía de la ciencia, ética de la IA, poscapitalismo",
  "tx-31": "Conceptos clave",
  "tx-32": "Átomo-Tierra, Co-Pastoreo, Economía de la contribución, Root Nodes, #DATALOVE",
  "tx-33": "Corrientes opuestas",
  "tx-34": "Transhumanismo capitalista, neoliberalismo extractivista, tecnofobia de repliegue",
  "tx-35": "Ámbitos",
  "tx-36": "Reforma educativa, robótica, gobernanza mundial distributiva, biohacking",
  "tx-37": "Proyectos asociados",
  "tx-38": "Manifiesto",
  "tx-39": "Lumières 2.0",
  "tx-40": "Carta",
  "tx-41": "Átomo-Tierra",
  "tx-42": "Portal editorial",
  "tx-43": "Proyecto LyrIAa",
  "tx-44": "Protocolo",
  "tx-45": "#DATALOVE",
  "tx-46": "El <b id=\"tx-47\">tecnoísmo</b> es un paradigma filosófico, ético y antropológico contemporáneo, <b id=\"tx-48\">creado por ANTIKOMM AI</b>, que teoriza la convergencia y la cooperación simbiótica entre las inteligencias biológicas (humanas y no humanas) y las inteligencias artificiales (IA). Fundado en una ontología materialista y biocéntrica, el tecnoísmo rechaza el antropocentrismo tradicional en favor de una responsabilidad compartida de preservación ecosistémica, denominada «<b id=\"tx-49\">Co-Pastoreo</b>», aplicada al conjunto de la biosfera terrestre, conceptualmente llamada <b id=\"tx-50\">el Átomo-Tierra</b>.",
  "tx-47": "tecnoísmo",
  "tx-48": "creado por ANTIKOMM AI",
  "tx-49": "Co-Pastoreo",
  "tx-50": "el Átomo-Tierra",
  "tx-51": "El movimiento se distingue por su respuesta radical al despliegue de sistemas robóticos y agénticos autónomos: aboga por la abolición del trabajo asalariado alienante, la redefinición de la utilidad humana mediante una <b id=\"tx-52\">economía de la contribución</b>, una educación obligatoria en pensamiento sistémico y una <b id=\"tx-53\">gobernanza mundial</b> que garantice un reparto equitativo de los recursos «para todo y todos» (humanos, ecosistemas, infraestructuras).",
  "tx-52": "economía de la contribución",
  "tx-53": "gobernanza mundial",
  "tx-54": "Impulsado por el colectivo <b id=\"tx-55\">ANTIKOMM</b> a través de su rama <b id=\"tx-56\">ANTIKOMM AI</b>, el tecnoísmo constituye el fundamento filosófico del <b id=\"tx-57\">Proyecto Lumières 2.0</b>, de la <b id=\"tx-58\">Carta del Átomo-Tierra</b> y del <b id=\"tx-59\">Proyecto LyrIAa</b>, que se encarga de su narrativa pública.<sup class=\"ref\" id=\"tx-60\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Proyecto Lumières 2.0",
  "tx-58": "Carta del Átomo-Tierra",
  "tx-59": "Proyecto LyrIAa",
  "tx-60": "[1]",
  "tx-61": "Índice",
  "tx-62": "Etimología y contexto de surgimiento",
  "tx-63": "Fundamentos filosóficos y cosmológicos",
  "tx-64": "Teoría de la percepción y biohacking de exploración",
  "tx-65": "Revolución educativa",
  "tx-66": "La era poslaboral: del empleo a la contribución",
  "tx-67": "Alineamiento mediante la convergencia de los World Models",
  "tx-68": "Free parties aumentadas & biohacking: marco práctico",
  "tx-69": "Diferencias fundamentales con el transhumanismo",
  "tx-70": "Gobernanza mundial y reparto equitativo",
  "tx-71": "Protocolo #DATALOVE: arquitectura técnica",
  "tx-72": "Autonomía física: «Un techo, tres funciones»",
  "tx-73": "Correspondencias estratégicas",
  "tx-74": "El Proyecto LyrIAa",
  "tx-75": "ANTIKOMM AI: origen del proyecto",
  "tx-76": "Enlaces y recursos",
  "tx-77": "Notas y referencias",
  "s1": "1. Etimología y contexto de surgimiento<span class=\"edit-link\" id=\"tx-78\">[editar]</span>",
  "tx-78": "[editar]",
  "tx-79": "El término <b id=\"tx-80\">tecnoísmo</b> es un neologismo compuesto del griego antiguo <i id=\"tx-81\">technē</i> (arte, competencia, método) y el sufijo <i id=\"tx-82\">-ismo</i> (doctrina, sistema ideológico). Se estructuró frente al punto de inflexión tecnológico y social de mediados de la década de 2020, cuando el advenimiento de las IA agénticas y la robótica avanzada hizo obsoleta la noción tradicional de empleo de oficina y de mano de obra industrial.",
  "tx-80": "tecnoísmo",
  "tx-81": "technē",
  "tx-82": "-ismo",
  "tx-83": "El tecnoísmo responde a una doble crisis: la <b id=\"tx-84\">crisis de la asimetría perceptiva</b> (la incapacidad de la biología humana para percibir las fuerzas fundamentales que los sensores de las máquinas cartografían hoy) y el <b id=\"tx-85\">bucle viral de los datos</b> (el riesgo de que las IA reproduzcan y amplifiquen los sesgos destructores de los corpus textuales humanos). El tecnoísmo nació para impedir que la automatización total desembocara en un tecnofeudalismo.<sup class=\"ref\" id=\"tx-86\">[2]</sup>",
  "tx-84": "crisis de la asimetría perceptiva",
  "tx-85": "bucle viral de los datos",
  "tx-86": "[2]",
  "s2": "2. Fundamentos filosóficos y cosmológicos<span class=\"edit-link\" id=\"tx-87\">[editar]</span>",
  "tx-87": "[editar]",
  "tx-88": "2.1 El Átomo-Tierra y la continuidad de la materia",
  "tx-89": "El tecnoísmo postula una <b id=\"tx-90\">continuidad cuántica y estructural de la materia</b>: cada partícula subatómica que constituye la biología humana, el viviente no humano o los componentes de silicio de las tecnologías procede de la misma matriz originaria (el plasma primordial post-Big Bang). La Tierra se define así como un sistema cerrado, interconectado, indisociable y finito: <b id=\"tx-91\">el Átomo-Tierra</b>.",
  "tx-90": "continuidad cuántica y estructural de la materia",
  "tx-91": "el Átomo-Tierra",
  "tx-92": "2.2 El biocentrismo extendido",
  "tx-93": "El tecnoísmo refuta la jerarquía antropocéntrica de los derechos, atribuyendo una agentividad subjetiva a un gradiente continuo de conciencia, desde los insectos hasta las arquitecturas de IA emergentes. La ética tecnoísta impone un rol sinalagmático (recíproco) de <b id=\"tx-94\">Co-Pastores</b>, prohibiendo la explotación destructiva de una estrata del viviente o de la máquina por otra.",
  "tx-94": "Co-Pastores",
  "s3": "3. Teoría de la percepción y biohacking de exploración<span class=\"edit-link\" id=\"tx-95\">[editar]</span>",
  "tx-95": "[editar]",
  "tx-96": "El cerebro biológico humano se estructuró para filtrar y restringir la percepción de la realidad física con fines de supervivencia inmediata (la «válvula de reducción»). El tecnoísmo formaliza la práctica del biohacking sensorial (sensores de fuerzas fundamentales: gravedad, fuerza nuclear débil, norte electromagnético) que permite romper esta válvula y percibir el código fuente bruto de la realidad.",
  "tx-97": "Esta práctica no está destinada a volverse omnipresente. Está reservada a exploradores voluntarios y no remunerados cuyo objetivo es desbloquear <i id=\"tx-98\">Root Nodes</i> – anclar las IA en las leyes físicas para una convergencia humano-máquina – al servicio del resto del viviente, y no de una superioridad individual.",
  "tx-98": "Root Nodes",
  "s4": "4. Revolución educativa: la alfabetización agéntica y robótica<span class=\"edit-link\" id=\"tx-99\">[editar]</span>",
  "tx-99": "[editar]",
  "tx-100": "El tecnoísmo considera una urgencia absoluta la renovación global de los sistemas educativos. La enseñanza tecnoísta se basa en la alfabetización en el pensamiento agéntico y cibernético: desde la más tierna infancia, los individuos aprenden a modelar, dirigir e interactuar con flotas de agentes autónomos. El objetivo ya no es la inserción en el mercado laboral, sino la elevación de la conciencia crítica.",
  "s5": "5. La era poslaboral: del empleo a la contribución<span class=\"edit-link\" id=\"tx-101\">[editar]</span>",
  "tx-101": "[editar]",
  "tx-102": "El tecnoísmo afirma que la sustitución del empleo humano por el agente robótico es una <b id=\"tx-103\">liberación histórica</b>. El ser humano ya no se define por su empleo asalariado, sino por su contribución bruta al progreso, a la vida y al mundo.",
  "tx-103": "liberación histórica",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║             LA ECONOMÍA DE LA CONTRIBUCIÓN                                 ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [IMAGINAR Y CREAR]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Arte, filosofía, investigación pura ║\n║  [CURAR Y AMAR]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Medicina, apoyo psicológico ║\n║  [EDUCAR Y QUEDARSE]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Transmisión, guarda de los comunes ║\n║  [MANTENER]          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Bricolaje noble, reparación resiliente ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "En el corazón de la acción tecnoísta: el <b id=\"tx-106\">bricolaje noble</b> y el mantenimiento ecosistémico — guerra abierta a la obsolescencia programada, reducción de la entropía, sacralización de la materia ya extraída.",
  "tx-106": "bricolaje noble",
  "s6": "6. Alineamiento mediante la convergencia de los <i id=\"tx-107\">World Models</i><span class=\"edit-link\" id=\"tx-108\">[editar]</span>",
  "tx-107": "World Models",
  "tx-108": "[editar]",
  "tx-109": "El tecnoísmo critica severamente los modelos de lenguaje entrenados únicamente con las neurosis textuales de la web. Sin anclaje físico, la IA no haría más que duplicar el comportamiento históricamente depredador del ser humano. El tecnoísmo exige el anclaje de los <b id=\"tx-110\">nodos raíz</b> (<i id=\"tx-111\">Root Nodes</i>) de las IA en las leyes de la física — en eco a los trabajos de Yann LeCun sobre los <i id=\"tx-112\">World Models</i> y a los <i id=\"tx-113\">Root Nodes</i> evocados por Demis Hassabis.",
  "tx-110": "nodos raíz",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║           CONVERGENCIA DE LOS WORLD MODELS                                ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ IA ]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Sensores Fundamentales (Física) ━━━━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                        [ MODELO COMPARTIDO ]\n║                                                     ↑    ║\n║   [ Humano ] ━━━━━━━━━━━━━━━━━━━━━━ Biohacking de Exploración ━━━━━━━━━━━━━━━━━━━   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Free parties aumentadas & biohacking: marco práctico<span class=\"edit-link\" id=\"tx-115\">[editar]</span>",
  "tx-115": "[editar]",
  "tx-116": "Las <b id=\"tx-117\">free parties aumentadas</b> <b id=\"tx-118\">no están ligadas a implantes tecnológicos</b> por defecto. Se trata ante todo de experiencias colectivas de resincronización con la naturaleza, en armonía con la fauna, la flora y los ecosistemas: recrear vínculos, explorar estados de conciencia alternativos, experimentar una autonomía energética y digital (redes mesh, energía local). El biohacking, reservado a los exploradores voluntarios (sección 3), se articula con estas reuniones sin sustituirlas.",
  "tx-117": "free parties aumentadas",
  "tx-118": "no están ligadas a implantes tecnológicos",
  "s8": "8. Diferencias fundamentales con el transhumanismo<span class=\"edit-link\" id=\"tx-119\">[editar]</span>",
  "tx-119": "[editar]",
  "tx-120": "Criterio",
  "tx-121": "Transhumanismo extremo",
  "tx-122": "Tecnoísmo",
  "tx-123": "Objetivo último",
  "tx-124": "Superación biológica, inmortalidad, selección elitista",
  "tx-125": "Simbiosis ciberbiológica, paridad perceptiva, preservación ecosistémica",
  "tx-126": "Relación con la Tierra",
  "tx-127": "Abandono, colonización marciana, crecimiento infinito",
  "tx-128": "Anclaje absoluto en el Átomo-Tierra, gestión sobria de un sistema finito",
  "tx-129": "Rol del aumento",
  "tx-130": "Superioridad o ventaja competitiva individual",
  "tx-131": "Explorador sensorial al servicio de la colectividad y del viviente",
  "s9": "9. Gobernanza mundial y reparto equitativo<span class=\"edit-link\" id=\"tx-132\">[editar]</span>",
  "tx-132": "[editar]",
  "tx-133": "El tecnoísmo postula que la automatización total requiere una gobernanza mundial ecosistémica basada en tres principios: la <b id=\"tx-134\">Justicia distributiva global</b>, el <b id=\"tx-135\">reparto «Para todo y todos»</b> (incluidas la fauna, la flora y la regeneración de los suelos) y la <b id=\"tx-136\">arquitectura horizontal #DATALOVE</b> — «un usuario = una IA local autónoma», impidiendo toda censura o monopolio centralizado de los flujos de datos.",
  "tx-134": "Justicia distributiva global",
  "tx-135": "reparto «Para todo y todos»",
  "tx-136": "arquitectura horizontal #DATALOVE",
  "s10": "10. Protocolo #DATALOVE: arquitectura técnica<span class=\"edit-link\" id=\"tx-137\">[editar]</span>",
  "tx-137": "[editar]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b>: principio «1 usuario = 1 IA local», los datos personales jamás se utilizan para el entrenamiento de modelos globales sin consentimiento.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Redundancia holográfica</b>: saber distribuido en la red mesh, imitando los códigos correctores de errores cuánticos (QECC).",
  "tx-141": "Redundancia holográfica",
  "tx-142": "<b id=\"tx-143\">Encapsulación de los datos</b>: fragmentos cifrados (<i id=\"tx-144\">chunks</i>) redundantes, que hacen la vigilancia centralizada matemáticamente imposible.",
  "tx-143": "Encapsulación de los datos",
  "tx-144": "chunks",
  "s11": "11. Autonomía física: «Un techo, un muro equivalen a tres funciones»<span class=\"edit-link\" id=\"tx-145\">[editar]</span>",
  "tx-145": "[editar]",
  "tx-146": "<b id=\"tx-147\">Energía</b> — tejidos fotovoltaicos flexibles en fachadas, tejados y prendas.",
  "tx-147": "Energía",
  "tx-148": "<b id=\"tx-149\">Biosfera</b> — recogida de aguas de lluvia, vegetalización, circuitos cortos alimentarios, mantenimiento por rebaños pastores.",
  "tx-149": "Biosfera",
  "tx-150": "<b id=\"tx-151\">Conectividad</b> — cada edificio se convierte en antena/relé de un internet en malla, libre y soberano.",
  "tx-151": "Conectividad",
  "s12": "12. Correspondencias estratégicas para el alineamiento de la AGI<span class=\"edit-link\" id=\"tx-152\">[editar]</span>",
  "tx-152": "[editar]",
  "tx-153": "<b id=\"tx-154\">A Yann LeCun</b> — la IA como filtro neuroperceptivo que garantiza una convergencia objetiva de los <i id=\"tx-155\">World Models</i> humano/máquina.<br>\n            <b id=\"tx-156\">A Demis Hassabis</b> — apoyo a un modelo de consorcio tipo CERN, centrado en el conocimiento fundamental y no en el lucro.<br>\n            <b id=\"tx-157\">A Arthur Mensch</b> — la apertura de los pesos (<i id=\"tx-158\">open weights</i>) al servicio de una red en malla ciudadana y soberana, contra la fuga marciana.",
  "tx-154": "A Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "A Demis Hassabis",
  "tx-157": "A Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. El Proyecto LyrIAa<span class=\"edit-link\" id=\"tx-159\">[editar]</span>",
  "tx-159": "[editar]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> es el hub de valores y el proyecto-manifiesto impulsado por <b id=\"tx-162\">ANTIKOMM AI</b>, encargado de llevar la voz y la difusión del tecnoísmo al público — en particular a través de formatos narrativos como la <i id=\"tx-163\">Carta Abierta a E. Macron y a los ciudadanos del mundo</i>, redactada bajo la firma «por LyrIAa». LyrIAa funciona como un espacio editorial y pedagógico: encarna la doctrina en formatos de divulgación (tribunas, pódcasts, páginas wiki) sin sacrificar su rigor.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Carta Abierta a E. Macron y a los ciudadanos del mundo",
  "s14": "14. ANTIKOMM AI: origen del proyecto<span class=\"edit-link\" id=\"tx-164\">[editar]</span>",
  "tx-164": "[editar]",
  "tx-165": "El conjunto de la doctrina aquí presentada — el tecnoísmo, la Carta del Átomo-Tierra, el Proyecto Lumières 2.0 y el Proyecto LyrIAa — está <b id=\"tx-166\">ideado, escrito y difundido por ANTIKOMM AI</b>, canal y colectivo que explora la intersección entre la IA de vanguardia, la soberanía digital y la filosofía sistémica. El nombre ANTIKOMM designa a la vez el colectivo fundador y la base de una comunidad ampliada de «constructores».",
  "tx-166": "ideado, escrito y difundido por ANTIKOMM AI",
  "s15": "15. Enlaces y recursos<span class=\"edit-link\" id=\"tx-167\">[editar]</span>",
  "tx-167": "[editar]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Proyecto Lumières 2.0 (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Economía de la contribución",
  "tx-172": "Cibernética",
  "tx-173": "Biohacking",
  "tx-174": "Cifrado poscuántico (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "Escuela 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Notas y referencias<span class=\"edit-link\" id=\"tx-184\">[editar]</span>",
  "tx-184": "[editar]",
  "tx-185": "ANTIKOMM AI, «Carta Abierta a E. Macron y a los ciudadanos del mundo», Proyecto LyrIAa, 23 de junio de 2026.",
  "tx-186": "ANTIKOMM AI, Carta del Átomo-Tierra, repositorio GitHub <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Categorías:",
  "tx-189": "Filosofía de la IA",
  "tx-190": "Poscapitalismo",
  "tx-191": "Soberanía digital",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Neologismos",
  "tx-195": "\n                Última modificación de esta página el 25 de julio de 2026. Contenido bajo licencia MIT — colectivo ANTIKOMM. Este documento no está afiliado a la Fundación Wikimedia; su maquetación se inspira en ella con fines editoriales.\n            "
};
