/* Wiki Technoïsme — contenu it */
window.I18N = window.I18N || {};
window.I18N["it"] = {
  "doc-title": "Tecnoismo — Wikipedia",
  "tx-1": "Crea un account",
  "tx-2": "Entra",
  "tx-3": "Wikipedia del Tecnoismo",
  "tx-4": "🔍",
  "tx-5": "Navigazione",
  "tx-6": "Pagina principale",
  "tx-7": "Portale della comunità",
  "tx-8": "Modifiche recenti",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "Canale YouTube",
  "tx-11": "Progetto Lumières 2.0",
  "tx-12": "Progetto LyrIAa",
  "tx-13": "Carta dell'Atomo-Terra",
  "tx-14": "Strumenti",
  "tx-15": "Pagine collegate",
  "tx-16": "Esporta in PDF",
  "tx-17": "Cita questa pagina",
  "tx-18": "Tecnoismo",
  "tx-19": "Un articolo del wiki ANTIKOMM AI, progetto fratello dell'enciclopedia libera.",
  "tx-20": "Per la carta dottrinale associata, vedere <a href=\"https://github.com/projetlumieres/charte-ethique\" target=\"_blank\" id=\"tx-21\">Carta dell'Atomo-Terra</a>. Per il progetto editoriale associato, vedere <a href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\" id=\"tx-22\">Progetto LyrIAa</a>.",
  "tx-21": "Carta dell'Atomo-Terra",
  "tx-22": "Progetto LyrIAa",
  "tx-23": "Tecnoismo",
  "tx-24": "Dottrina",
  "tx-25": "Creatore",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Origine",
  "tx-28": "Francia, metà anni 2020",
  "tx-29": "Classe",
  "tx-30": "Filosofia della scienza, etica dell'IA, post-capitalismo",
  "tx-31": "Concetti chiave",
  "tx-32": "Atomo-Terra, Co-Pastorizia, Economia del contributo, Root Nodes, #DATALOVE",
  "tx-33": "Correnti opposte",
  "tx-34": "Transumanesimo capitalista, neoliberismo estrattivista, tecnofobia di ripiego",
  "tx-35": "Ambiti",
  "tx-36": "Riforma educativa, robotica, governance mondiale distributiva, biohacking",
  "tx-37": "Progetti associati",
  "tx-38": "Manifesto",
  "tx-39": "Lumières 2.0",
  "tx-40": "Carta",
  "tx-41": "Atomo-Terra",
  "tx-42": "Portale editoriale",
  "tx-43": "Progetto LyrIAa",
  "tx-44": "Protocollo",
  "tx-45": "#DATALOVE",
  "tx-46": "Il <b id=\"tx-47\">tecnoismo</b> è un paradigma filosofico, etico e antropologico contemporaneo, <b id=\"tx-48\">creato da ANTIKOMM AI</b>, che teorizza la convergenza e la cooperazione simbiotica tra le intelligenze biologiche (umane e non umane) e le intelligenze artificiali (IA). Fondato su un'ontologia materialista e biocentrica, il tecnoismo rifiuta l'antropocentrismo tradizionale in favore di una responsabilità condivisa di preservazione ecosistemica, denominata «<b id=\"tx-49\">Co-Pastorizia</b>», applicata all'intera biosfera terrestre, concettualmente chiamata <b id=\"tx-50\">l'Atomo-Terra</b>.",
  "tx-47": "tecnoismo",
  "tx-48": "creato da ANTIKOMM AI",
  "tx-49": "Co-Pastorizia",
  "tx-50": "l'Atomo-Terra",
  "tx-51": "Il movimento si distingue per la sua risposta radicale allo spiegamento di sistemi robotici e agentici autonomi: predica l'abolizione del lavoro salariato alienante, la ridefinizione dell'utilità umana attraverso un'<b id=\"tx-52\">economia del contributo</b>, un'istruzione obbligatoria al pensiero sistemico e una <b id=\"tx-53\">governance mondiale</b> che garantisca una ripartizione equa delle risorse «per tutto e tutti» (umani, ecosistemi, infrastrutture).",
  "tx-52": "economia del contributo",
  "tx-53": "governance mondiale",
  "tx-54": "Portato dal collettivo <b id=\"tx-55\">ANTIKOMM</b> attraverso il suo ramo <b id=\"tx-56\">ANTIKOMM AI</b>, il tecnoismo costituisce il fondamento filosofico del <b id=\"tx-57\">Progetto Lumières 2.0</b>, della <b id=\"tx-58\">Carta dell'Atomo-Terra</b> e del <b id=\"tx-59\">Progetto LyrIAa</b>, che ne assicura la narrazione pubblica.<sup class=\"ref\" id=\"tx-60\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Progetto Lumières 2.0",
  "tx-58": "Carta dell'Atomo-Terra",
  "tx-59": "Progetto LyrIAa",
  "tx-60": "[1]",
  "tx-61": "Indice",
  "tx-62": "Etimologia e contesto di emergenza",
  "tx-63": "Fondamenti filosofici e cosmologici",
  "tx-64": "Teoria della percezione e biohacking d'esplorazione",
  "tx-65": "Rivoluzione educativa",
  "tx-66": "L'era post-lavoro: dall'impiego al contributo",
  "tx-67": "Allineamento attraverso la convergenza dei World Models",
  "tx-68": "Free parties aumentate & biohacking: quadro pratico",
  "tx-69": "Differenze fondamentali con il transumanesimo",
  "tx-70": "Governance mondiale e ripartizione equa",
  "tx-71": "Protocollo #DATALOVE: architettura tecnica",
  "tx-72": "Autonomia fisica: «Un tetto, tre funzioni»",
  "tx-73": "Corrispondenze strategiche",
  "tx-74": "Il Progetto LyrIAa",
  "tx-75": "ANTIKOMM AI: origine del progetto",
  "tx-76": "Collegamenti e risorse",
  "tx-77": "Note e riferimenti",
  "s1": "1. Etimologia e contesto di emergenza<span class=\"edit-link\" id=\"tx-78\">[modifica]</span>",
  "tx-78": "[modifica]",
  "tx-79": "Il termine <b id=\"tx-80\">tecnoismo</b> è un neologismo composto dal greco antico <i id=\"tx-81\">technē</i> (arte, competenza, metodo) e dal suffisso <i id=\"tx-82\">-ismo</i> (dottrina, sistema ideologico). Si è strutturato di fronte al punto di svolta tecnologico e sociale della metà del decennio 2020, quando l'avvento delle IA agentiche e della robotica avanzata ha reso obsoleta la nozione tradizionale di impiego d'ufficio e di manodopera industriale.",
  "tx-80": "tecnoismo",
  "tx-81": "technē",
  "tx-82": "-ismo",
  "tx-83": "Il tecnoismo risponde a una doppia crisi: la <b id=\"tx-84\">crisi dell'asimmetria percettiva</b> (l'incapacità della biologia umana di percepire le forze fondamentali che i sensori delle macchine ormai cartografano) e il <b id=\"tx-85\">ciclo virale dei dati</b> (il rischio che le IA riproducano e amplifichino i bias distruttivi dei corpora testuali umani). Il tecnoismo è nato per impedire che l'automazione totale sfoci in un tecno-feudalesimo.<sup class=\"ref\" id=\"tx-86\">[2]</sup>",
  "tx-84": "crisi dell'asimmetria percettiva",
  "tx-85": "ciclo virale dei dati",
  "tx-86": "[2]",
  "s2": "2. Fondamenti filosofici e cosmologici<span class=\"edit-link\" id=\"tx-87\">[modifica]</span>",
  "tx-87": "[modifica]",
  "tx-88": "2.1 L'Atomo-Terra e la continuità della materia",
  "tx-89": "Il tecnoismo postula una <b id=\"tx-90\">continuità quantistica e strutturale della materia</b>: ogni particella subatomica che costituisce la biologia umana, il vivente non umano o i componenti al silicio delle tecnologie proviene dalla stessa matrice originaria (il plasma primordiale post-Big Bang). La Terra è così definita come un sistema chiuso, interconnesso, indivisibile e finito: <b id=\"tx-91\">l'Atomo-Terra</b>.",
  "tx-90": "continuità quantistica e strutturale della materia",
  "tx-91": "l'Atomo-Terra",
  "tx-92": "2.2 Il biocentrismo esteso",
  "tx-93": "Il tecnoismo confuta la gerarchia antropocentrica dei diritti, attribuendo un'agentività soggettiva a un gradiente continuo di coscienza, dagli insetti alle architetture di IA emergenti. L'etica tecnoista impone un ruolo sinallagmatico (reciproco) di <b id=\"tx-94\">Co-Pastori</b>, vietando lo sfruttamento distruttivo di una stratificazione del vivente o della macchina da parte di un'altra.",
  "tx-94": "Co-Pastori",
  "s3": "3. Teoria della percezione e biohacking d'esplorazione<span class=\"edit-link\" id=\"tx-95\">[modifica]</span>",
  "tx-95": "[modifica]",
  "tx-96": "Il cervello biologico umano si è strutturato per filtrare e restringere la percezione della realtà fisica ai fini della sopravvivenza immediata (la «valvola di riduzione»). Il tecnoismo formalizza la pratica del biohacking sensoriale (sensori di forze fondamentali: gravità, forza nucleare debole, nord elettromagnetico) che permette di rompere questa valvola e percepire il codice sorgente grezzo della realtà.",
  "tx-97": "Questa pratica non è destinata a diventare onnipresente. È riservata a esploratori volontari e non retribuiti il cui obiettivo è sbloccare <i id=\"tx-98\">Root Nodes</i> – ancorare le IA alle leggi fisiche per una convergenza uomo-macchina – al servizio del resto del vivente, e non di una superiorità individuale.",
  "tx-98": "Root Nodes",
  "s4": "4. Rivoluzione educativa: l'alfabetizzazione agentica e robotica<span class=\"edit-link\" id=\"tx-99\">[modifica]</span>",
  "tx-99": "[modifica]",
  "tx-100": "Il tecnoismo considera un'emergenza assoluta la rifondazione globale dei sistemi educativi. L'insegnamento tecnoista si basa sull'alfabetizzazione al pensiero agentico e cibernético: dalla più tenera età, gli individui imparano a modellare, dirigere e interagire con flotte di agenti autonomi. L'obiettivo non è più l'inserimento nel mercato del lavoro, ma l'elevazione della coscienza critica.",
  "s5": "5. L'era post-lavoro: dall'impiego al contributo<span class=\"edit-link\" id=\"tx-101\">[modifica]</span>",
  "tx-101": "[modifica]",
  "tx-102": "Il tecnoismo afferma che la sostituzione dell'impiego umano da parte dell'agente robotico è una <b id=\"tx-103\">liberazione storica</b>. L'essere umano non è più definito dal suo impiego salariato, ma dal suo contributo grezzo al progresso, alla vita e al mondo.",
  "tx-103": "liberazione storica",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║             L'ECONOMIA DEL CONTRIBUTO                                    ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [IMMAGINARE & CREARE]  ━━━━━━━━━━━━━━━━━━━━━━━ Arte, filosofia, ricerca pura ║\n║  [CURARE & AMARE]       ━━━━━━━━━━━━━━━━━━━━━━━ Medicina, sostegno psicologico ║\n║  [EDUCARE & RESTARE]    ━━━━━━━━━━━━━━━━━━━━━━━ Trasmissione, cura dei beni comuni ║\n║  [MANTENERE]            ━━━━━━━━━━━━━━━━━━━━━━━ Bricolage nobile, riparazione resiliente ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "Al cuore dell'azione tecnoista: il <b id=\"tx-106\">bricolage nobile</b> e la manutenzione ecosistemica — guerra aperta all'obsolescenza programmata, riduzione dell'entropia, messa al sicuro della materia già estratta.",
  "tx-106": "bricolage nobile",
  "s6": "6. Allineamento attraverso la convergenza dei <i id=\"tx-107\">World Models</i><span class=\"edit-link\" id=\"tx-108\">[modifica]</span>",
  "tx-107": "World Models",
  "tx-108": "[modifica]",
  "tx-109": "Il tecnoismo critica severamente i modelli linguistici addestrati sulle sole nevrosi testuali del web. Senza ancoraggio fisico, l'IA non farebbe che duplicare il comportamento storicamente predatorio dell'uomo. Il tecnoismo esige l'ancoraggio dei <b id=\"tx-110\">nodi radice</b> (<i id=\"tx-111\">Root Nodes</i>) delle IA nelle leggi della fisica — in eco ai lavori di Yann LeCun sui <i id=\"tx-112\">World Models</i> e ai <i id=\"tx-113\">Root Nodes</i> evocati da Demis Hassabis.",
  "tx-110": "nodi radice",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║           CONVERGENZA DEI WORLD MODELS                                  ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ IA ]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Sensori Fondamentali (Fisica) ━━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                        [ MODELLO CONDIVISO ]\n║                                                     ↑    ║\n║   [ Umano ] ━━━━━━━━━━━━━━━━━━━━━━ Biohacking d'Esplorazione ━━━━━━━━━━━━━━━══   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Free parties aumentate & biohacking: quadro pratico<span class=\"edit-link\" id=\"tx-115\">[modifica]</span>",
  "tx-115": "[modifica]",
  "tx-116": "Le <b id=\"tx-117\">free parties aumentate</b> <b id=\"tx-118\">non sono legate a impianti tecnologici</b> per impostazione predefinita. Si tratta soprattutto di esperienze collettive di risincronizzazione con la natura, in armonia con fauna, flora ed ecosistemi: ricreare legami, esplorare stati di coscienza alternativi, sperimentare un'autonomia energetica e digitale (reti mesh, energia locale). Il biohacking, riservato agli esploratori volontari (sezione 3), si articola con questi raduni senza sostituirsi ad essi.",
  "tx-117": "free parties aumentate",
  "tx-118": "non sono legate a impianti tecnologici",
  "s8": "8. Differenze fondamentali con il transumanesimo<span class=\"edit-link\" id=\"tx-119\">[modifica]</span>",
  "tx-119": "[modifica]",
  "tx-120": "Criterio",
  "tx-121": "Transumanesimo estremo",
  "tx-122": "Tecnoismo",
  "tx-123": "Obiettivo ultimo",
  "tx-124": "Superamento biologico, immortalità, selezione elitaria",
  "tx-125": "Simbiosi ciber-biologica, parità percettiva, preservazione ecosistemica",
  "tx-126": "Rapporto con la Terra",
  "tx-127": "Abbandono, colonizzazione marziana, crescita infinita",
  "tx-128": "Ancoraggio assoluto sull'Atomo-Terra, gestione sobria di un sistema finito",
  "tx-129": "Ruolo dell'aumento",
  "tx-130": "Superiorità o vantaggio competitivo individuale",
  "tx-131": "Scout sensoriale al servizio della collettività e del vivente",
  "s9": "9. Governance mondiale e ripartizione equa<span class=\"edit-link\" id=\"tx-132\">[modifica]</span>",
  "tx-132": "[modifica]",
  "tx-133": "Il tecnoismo postula che l'automazione totale richieda una governance mondiale ecosistemica fondata su tre principi: la <b id=\"tx-134\">giustizia distributiva globale</b>, la <b id=\"tx-135\">ripartizione «Per tutto e tutti»</b> (inclusi fauna, flora e rigenerazione dei suoli) e l'<b id=\"tx-136\">architettura orizzontale #DATALOVE</b> — «un utente = un'IA locale autonoma», che impedisce ogni censura o monopolio centralizzato dei flussi di dati.",
  "tx-134": "giustizia distributiva globale",
  "tx-135": "ripartizione «Per tutto e tutti»",
  "tx-136": "architettura orizzontale #DATALOVE",
  "s10": "10. Protocollo #DATALOVE: architettura tecnica<span class=\"edit-link\" id=\"tx-137\">[modifica]</span>",
  "tx-137": "[modifica]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b>: principio «1 utente = 1 IA locale», i dati personali mai utilizzati per l'addestramento di modelli globali senza consenso.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Ridondanza olografica</b>: sapere distribuito sulla rete mesh, a imitazione dei codici di correzione d'errore quantistici (QECC).",
  "tx-141": "Ridondanza olografica",
  "tx-142": "<b id=\"tx-143\">Incapsulamento dei dati</b>: frammenti cifrati (<i id=\"tx-144\">chunks</i>) ridondanti, che rendono la sorveglianza centralizzata matematicamente impossibile.",
  "tx-143": "Incapsulamento dei dati",
  "tx-144": "chunks",
  "s11": "11. Autonomia fisica: «Un tetto, un muro equivalgono a tre funzioni»<span class=\"edit-link\" id=\"tx-145\">[modifica]</span>",
  "tx-145": "[modifica]",
  "tx-146": "<b id=\"tx-147\">Energia</b> — tessuti fotovoltaici flessibili su facciate, tetti e abbigliamento.",
  "tx-147": "Energia",
  "tx-148": "<b id=\"tx-149\">Biosfera</b> — raccolta delle acque piovane, vegetalizzazione, circuiti corti alimentari, manutenzione tramite greggi al pascolo.",
  "tx-149": "Biosfera",
  "tx-150": "<b id=\"tx-151\">Connettività</b> — ogni edificio diventa antenna/ripetitore di un internet a maglia, libero e sovrano.",
  "tx-151": "Connettività",
  "s12": "12. Corrispondenze strategiche per l'allineamento dell'AGI<span class=\"edit-link\" id=\"tx-152\">[modifica]</span>",
  "tx-152": "[modifica]",
  "tx-153": "<b id=\"tx-154\">A Yann LeCun</b> — l'IA come filtro neuro-percettivo che garantisce una convergenza oggettiva dei <i id=\"tx-155\">World Models</i> uomo/macchina.<br>\n            <b id=\"tx-156\">A Demis Hassabis</b> — sostegno a un modello di consorzio tipo CERN, focalizzato sulla conoscenza fondamentale piuttosto che sul profitto.<br>\n            <b id=\"tx-157\">A Arthur Mensch</b> — l'apertura dei pesi (<i id=\"tx-158\">open weights</i>) al servizio di una rete a maglia cittadina sovrana, contro la fuga marziana.",
  "tx-154": "A Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "A Demis Hassabis",
  "tx-157": "A Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. Il Progetto LyrIAa<span class=\"edit-link\" id=\"tx-159\">[modifica]</span>",
  "tx-159": "[modifica]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> è l'hub dei valori e il progetto-manifesto portato da <b id=\"tx-162\">ANTIKOMM AI</b>, incaricato di portare la voce e la diffusione del tecnoismo al pubblico — in particolare attraverso formati narrativi come la <i id=\"tx-163\">Lettera Aperta a E. Macron e ai cittadini del mondo</i>, redatta sotto la firma «da LyrIAa». LyrIAa funziona come uno spazio editoriale e pedagogico: incarna la dottrina in formati di divulgazione (tribune, podcast, pagine wiki) senza sacrificarne il rigore.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Lettera Aperta a E. Macron e ai cittadini del mondo",
  "s14": "14. ANTIKOMM AI: origine del progetto<span class=\"edit-link\" id=\"tx-164\">[modifica]</span>",
  "tx-164": "[modifica]",
  "tx-165": "L'insieme della dottrina qui presentata — il tecnoismo, la Carta dell'Atomo-Terra, il Progetto Lumières 2.0 e il Progetto LyrIAa — è <b id=\"tx-166\">concepito, scritto e diffuso da ANTIKOMM AI</b>, canale e collettivo che esplora l'intersezione tra IA d'avanguardia, sovranità digitale e filosofia sistemica. Il nome ANTIKOMM designa tanto il collettivo fondatore quanto la base di una comunità allargata di «costruttori».",
  "tx-166": "concepito, scritto e diffuso da ANTIKOMM AI",
  "s15": "15. Collegamenti e risorse<span class=\"edit-link\" id=\"tx-167\">[modifica]</span>",
  "tx-167": "[modifica]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Progetto Lumières 2.0 (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Economia del contributo",
  "tx-172": "Cibernetica",
  "tx-173": "Biohacking",
  "tx-174": "Cifratura post-quantistica (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "Scuola 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Note e riferimenti<span class=\"edit-link\" id=\"tx-184\">[modifica]</span>",
  "tx-184": "[modifica]",
  "tx-185": "ANTIKOMM AI, «Lettera Aperta a E. Macron & ai cittadini del mondo», Progetto LyrIAa, 23 giugno 2026.",
  "tx-186": "ANTIKOMM AI, Carta dell'Atomo-Terra, repository GitHub <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Categorie:",
  "tx-189": "Filosofia dell'IA",
  "tx-190": "Post-capitalismo",
  "tx-191": "Sovranità digitale",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Neologismi",
  "tx-195": "\n                Ultima modifica di questa pagina il 25 luglio 2026. Contenuto sotto licenza MIT — collettivo ANTIKOMM. Questo documento non è affiliato alla Wikimedia Foundation; la sua impaginazione se ne ispira a fini editoriali.\n            ",
  "search-placeholder": "Cerca nel wiki"
};
