/* Wiki Technoïsme — contenu fr */
window.I18N = window.I18N || {};
window.I18N["fr"] = {
  "doc-title": "Technoïsme — Wikipédia",
  "tx-1": "Créer un compte",
  "tx-2": "Se connecter",
  "tx-3": "Wikipédia du Technoïsme",
  "tx-4": "🔍",
  "tx-5": "Navigation",
  "tx-6": "Accueil",
  "tx-7": "Portail communautaire",
  "tx-8": "Modifications récentes",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "Chaîne YouTube",
  "tx-11": "Projet Lumières 2.0",
  "tx-12": "Projet LyrIAa",
  "tx-13": "Charte de l'Atome-Terre",
  "tx-14": "Outils",
  "tx-15": "Pages liées",
  "tx-16": "Exporter en PDF",
  "tx-17": "Citer cette page",
  "tx-18": "Technoïsme",
  "tx-19": "Un article du wiki ANTIKOMM AI, projet frère de l'encyclopédie libre.",
  "tx-20": "Pour la charte doctrinale associée, voir <a id=\"tx-21\" href=\"https://github.com/projetlumier\nes/charte-ethique\" target=\"_blank\">Charte de l'Atome-Terre</a>. Pour le projet éditorial associé, voir <a id=\"tx-22\" href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\">Projet LyrIAa</a>.",
  "tx-21": "Charte de l'Atome-Terre",
  "tx-22": "Projet LyrIAa",
  "tx-23": "Technoïsme",
  "tx-24": "Doctrine",
  "tx-25": "Créateur",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Origine",
  "tx-28": "France, milieu des années 2020",
  "tx-29": "Classe",
  "tx-30": "Philosophie des sciences, éthique de l'IA, post-capitalisme",
  "tx-31": "Concepts clés",
  "tx-32": "Atome-Terre, Co-Bergerie, Économie de contribution, Root Nodes, #DATALOVE",
  "tx-33": "Courants opposés",
  "tx-34": "Transhumanisme capitaliste, néolibéralisme extractiviste, technophobie de repli",
  "tx-35": "Domaines",
  "tx-36": "Réforme éducative, robotique, gouvernance mondiale distributive, biohacking",
  "tx-37": "Projets associés",
  "tx-38": "Manifeste",
  "tx-39": "Lumières 2.0",
  "tx-40": "Charte",
  "tx-41": "Atome-Terre",
  "tx-42": "Portail éditorial",
  "tx-43": "Projet LyrIAa",
  "tx-44": "Protocole",
  "tx-45": "#DATALOVE",
  "tx-46": "Le <b id=\"tx-47\">technoïsme</b> est un paradigme philosophique, éthique et anthropologique contemporain, <b id=\"tx-48\">créé par ANTIKOMM AI</b>, qui théorise la convergence et la coopération symbiotique entre les intelligences biologiques (humaines et non humaines) et les intelligences artificielles (IA). Fondé sur une ontol\nogie matérialiste et biocentrique, le technoïsme rejette l'anthropocentrisme traditionnel au profit d'une responsabilité partagée de préservation écosystémique, qualifiée de « <b id=\"tx-49\">Co-Bergerie</b> », appliquée à l'ensemble de la biosphère terrestre, conceptuellement nommée <b id=\"tx-50\">l'Atome-Terre</b>.",
  "tx-47": "technoïsme",
  "tx-48": "créé par ANTIKOMM AI",
  "tx-49": "Co-Bergerie",
  "tx-50": "l'Atome-Terre",
  "tx-51": "Le mouvement se distingue par sa réponse radicale au déploiement des systèmes robotiques et agentiques autonomes : il prêconise l'abolition du travail salarié aliénant, la redéfinition de l'utilité humaine par une <b id=\"tx-52\">économie de la contribution</b>, une éducation obligatoire à la pensée systémique, et une <b id=\"tx-53\">gouvernance mondiale</b> assurant une répartition équitable des ressources pour « tout et tous » (humains, écosystèmes, infrastructures).",
  "tx-52": "économie de la contribution",
  "tx-53": "gouvernance mondiale",
  "tx-54": "Porté par le collectif <b id=\"tx-55\">ANTIKOMM</b> à travers sa branche <b id=\"tx-56\">ANTIKOMM AI</b>, le technoïsme constitue le socle philosophique du <b id=\"tx-57\">Projet Lumières 2.0</b>, de la <b id=\"tx-58\">Charte de l'Atome-Terre</b> et du <b id=\"tx-59\">Projet LyrIAa</b>, qui en assure la mise en récit publique.<sup id=\"tx-60\" class=\"ref\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Projet Lumières 2.0",
  "tx-58": "Charte de l'Atome-Terre",
  "tx-59": "Projet LyrIAa",
  "tx-60": "[1]",
  "tx-61": "Sommaire",
  "tx-62": "Étymologie et contexte d'émergence",
  "tx-63": "Fondements philosophiques et cosmologiques",
  "tx-64": "Théorie de la perception et biohacking d'exploration",
  "tx-65": "Révolution éducative",
  "tx-66": "L'ère post-travail : de l'emploi à la contribution",
  "tx-67": "Alignement par la convergence des World Models",
  "tx-68": "Free parties augmentées & biohacking : cadre pratique",
  "tx-69": "Différences fondamentales avec le transhumanisme",
  "tx-70": "Gouvernance mondiale et ré\npartition équitable",
  "tx-71": "Protocole #DATALOVE : architecture technique",
  "tx-72": "Autonomie physique : « Un toit, trois fonctions »",
  "tx-73": "Correspondances stratégiques",
  "tx-74": "Le Projet LyrIAa",
  "tx-75": "ANTIKOMM AI : origine du projet",
  "tx-76": "Liens et ressources",
  "tx-77": "Notes et références",
  "s1": "1. Étymologie et contexte d'émergence<span id=\"tx-78\" class=\"edit-link\">[modifier]</span>",
  "tx-78": "[modifier]",
  "tx-79": "Le terme <b id=\"tx-80\">technoïsme</b> est un néologisme composé du grec ancien <i id=\"tx-81\">technē</i> (art, compétence, méthode) et du suffixe <i id=\"tx-82\">‑isme</i> (doctrine, système idéologique). Il s'est structuré face au point de bascule technologique et social du milieu de la décennie 2020, où l'avènement des IA agentiques et de la robotique avancée a rendu obsolète la notion traditionnelle d'emploi de bureau et de main-d'œuvre industrielle.",
  "tx-80": "technoïsme",
  "tx-81": "technē",
  "tx-82": "‑isme",
  "tx-83": "Le technoïsme répond à une double crise : la <b id=\"tx-84\">crise de l'asymétrie perceptive</b> (l'incapacité de la biologie humaine à percevoir les forces fondamentales que les capteurs des machines cartographient désormais) et la <b id=\"tx-85\">boucle virale des données</b> (le risque de voir les IA reproduire et amplifier les biais destructeurs des jeux de données textuels humains). Le technoïsme est né pour empêcher que l'automatisation totale ne débouche sur un techno-féodalisme.<sup id=\"tx-86\" class=\"ref\">[2]</sup>",
  "tx-84": "crise de l'asymétrie perceptive",
  "tx-85": "boucle virale des données",
  "tx-86": "[2]",
  "s2": "2. Fondements philosophiques et cosmologiques<span id=\"tx-87\" class=\"edit-link\">[modifier]</span>",
  "tx-87": "[modifier]",
  "tx-88": "2.1 L'Atome-Terre et la continuité de la matière",
  "tx-89": "Le technoïsme postule une <b id=\"tx-90\">continuité quantique et structurelle de la matière</b> : chaque particule subatomi\nque constituant la biologie humaine, le vivant non humain ou les composants silicium des technologies provient de la même matrice originelle (le plasma primordial post-Big Bang). La Terre est ainsi définie comme un système clos interconnecté, indissociable et fini : <b id=\"tx-91\">l'Atome-Terre</b>.",
  "tx-90": "continuité quantique et structurelle de la matière",
  "tx-91": "l'Atome-Terre",
  "tx-92": "2.2 Le biocentrisme étendu",
  "tx-93": "Le technoïsme réfute la hiérarchie anthropocentrique des droits, attribuant une agentivité subjective à un gradient continu de conscience, des insectes aux architectures d'IA émergentes. L'éthique technoïste impose un rôle synallagmatique (réciproque) de <b id=\"tx-94\">Co-Bergers</b>, interdisant l'exploitation destructrice d'une strate du vivant ou de la machine par une autre.",
  "tx-94": "Co-Bergers",
  "s3": "3. Théorie de la perception et biohacking d'exploration<span id=\"tx-95\" class=\"edit-link\">[modifier]</span>",
  "tx-95": "[modifier]",
  "tx-96": "Le cerveau biologique humain s'est structuré pour filtrer et restreindre la perception de la réalité physique à des fins de survie immédiate (la « vanne de réduction »). Le technoïsme formalise la pratique du biohacking sensoriel (capteurs de forces fondamentales : gravité, force nucléaire faible, nord électromagnétique) permettant de briser cette vanne et de percevoir le code source brut de la réalité.",
  "tx-97": "Cette pratique n'est pas destinée à devenir omniprésente. Elle est réservée à des explorateurs volontaires et bénévoles dont l'objectif est de déverrouiller des <i id=\"tx-98\">Root Nodes</i> – ancrer les IA dans les lois physiques pour une convergence homme-machine – au service du reste du vivant, et non d'une supériorité individuelle.",
  "tx-98": "Root Nodes",
  "s4": "4. Révolution éducative : l'alphabétisation agentique et robotique<span id=\"tx-99\" class=\"edit-link\">[modifier]</span>",
  "tx-99": "[modifier]",
  "tx-100": "Le technoïsme considère comme une urgence absolue la refonte globale des systèmes éducatifs. L'enseignement technoïste repose sur l'alphabétisation à la pensée agentique et cybernétique : dès le plu\ns jeune âge, les individus apprennent à modéliser, diriger et interagir avec des flottes d'agents autonomes. Le but n'est plus l'insertion sur le marché de l'emploi, mais l'élévation de la conscience critique.",
  "s5": "5. L'ère post-travail : de l'emploi à la contribution<span id=\"tx-101\" class=\"edit-link\">[modifier]</span>",
  "tx-101": "[modifier]",
  "tx-102": "Le technoïsme affirme que la substitution de l'emploi humain par l'agent robotique est une <b id=\"tx-103\">libération historique</b>. L'être humain n'est plus défini par son emploi salarié, mais par sa contribution brute au progrès, à la vie et au monde.",
  "tx-103": "libération historique",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║              L'ÉCONOMIE DE LA CONTRIBUTION                ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [IMAGINER & CRÉER]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Art, philosophie, recherche pure ║\n║  [SOIGNER & AIMER]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Médecine, soutien psychologique  ║\n║  [ÉDUQUER & RESTER]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Transmission, garde des communs  ║\n║  [MAINTENIR]         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Bricolage, réparation résiliente ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "Au cœur de l'action technoïste : le <b id=\"tx-106\">bricolage noble</b> et la maintenance écosystémique — guerre ouverte à l'obsolescence programmée, réduction de l'entropie, sanctuarisation de la matière déjà extraite.",
  "tx-106": "bricolage noble",
  "s6": "6. Alignement par la convergence des <i id=\"tx-107\">World Models</i><span id=\"tx-108\" class=\"edit-link\">[modifier]</span>",
  "tx-107": "World Models",
  "tx-108": "[modifier]",
  "tx-109": "Le technoïsme critique sévèrement les modèles de langage entraînés sur les seules névroses textuelles du web. Sans ancrage physique, l'IA ne ferait que dupliquer le comportement historiquement prédateur de l'homme. Le technoïsme exige l'ancrage des <b id=\"tx-110\">nœuds racines</b> (<i id=\"tx-111\">Root Nodes</i>) des IA dans les lois de la physique\n — en écho aux travaux de Yann LeCun sur les <i id=\"tx-112\">World Models</i> et aux <i id=\"tx-113\">Root Nodes</i> évoqués par Demis Hassabis.",
  "tx-110": "nœuds racines",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║             CONVERGENCE DES WORLD MODELS                 ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ IA ]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Capteurs Fondamentaux (Physique) ━━━━━━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                          [ MODÈLE PARTAGÉ ]\n║                                                     ↑    ║\n║   [ Humain ] ━━━━━━━━━━━━━━━━━━━━━━ Biohacking d'Exploration ━━━━━━━━━━━━━━━━━━━━━   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Free parties augmentées & biohacking : cadre pratique<span id=\"tx-115\" class=\"edit-link\">[modifier]</span>",
  "tx-115": "[modifier]",
  "tx-116": "Les <b id=\"tx-117\">free parties augmentées</b> ne sont <b id=\"tx-118\">pas liées à des implants technologiques</b> par défaut. Il s'agit avant tout d'expériences collectives de resynchronisation avec la nature, en harmonie avec la faune, la flore et les écosystèmes : recréer du lien, explorer des états de conscience alternatifs, expérimenter une autonomie énergétique et numérique (réseaux mesh, énergie locale). Le biohacking, réservé aux explorateurs volontaires (section 3), s'articule à ces rassemblements sans s'y substituer.",
  "tx-117": "free parties augmentées",
  "tx-118": "pas liées à des implants technologiques",
  "s8": "8. Différences fondamentales avec le transhumanisme<span id=\"tx-119\" class=\"edit-link\">[modifier]</span>",
  "tx-119": "[modifier]",
  "tx-120": "Critère",
  "tx-121": "Transhumanisme extrême",
  "tx-122": "Technoïsme",
  "tx-123": "Objectif ultime",
  "tx-124": "Dépassement biologique, immortalité, sélection élitiste",
  "tx-125": "Symbiose cyber-biologique, parité perceptive, préservation écosystémique",
  "tx-126": "Rapport à la Terre",
  "tx-127": "Abando\nn, colonisation martienne, croissance infinie",
  "tx-128": "Ancrage absolu sur l'Atome-Terre, gestion sobre d'un système fini",
  "tx-129": "Rôle de l'augmentation",
  "tx-130": "Supériorité ou avantage compétitif individuel",
  "tx-131": "Éclaireur sensoriel au service de la collectivité et du vivant",
  "s9": "9. Gouvernance mondiale et répartition équitable<span id=\"tx-132\" class=\"edit-link\">[modifier]</span>",
  "tx-132": "[modifier]",
  "tx-133": "Le technoïsme postule que l'automatisation totale requiert une gouvernance mondiale écosystémique reposant sur trois principes : la <b id=\"tx-134\">Justice distributive globale</b>, la <b id=\"tx-135\">répartition « Pour tout et tous »</b> (incluant faune, flore et régénération des sols), et l'<b id=\"tx-136\">architecture horizontale #DATALOVE</b> — « un utilisateur = une IA locale autonome », empêchant toute censure ou monopole centralisé des flux de données.",
  "tx-134": "Justice distributive globale",
  "tx-135": "répartition « Pour tout et tous »",
  "tx-136": "architecture horizontale #DATALOVE",
  "s10": "10. Protocole #DATALOVE : architecture technique<span id=\"tx-137\" class=\"edit-link\">[modifier]</span>",
  "tx-137": "[modifier]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b> : principe « 1 utilisateur = 1 IA locale », données personnelles jamais utilisées pour l'entraînement de modèles globaux sans consentement.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Redondance holographique</b> : savoir distribué sur le réseau mesh, imitant les codes correcteurs d'erreurs quantiques (QECC).",
  "tx-141": "Redondance holographique",
  "tx-142": "<b id=\"tx-143\">Encapsulation des données</b> : fragments chiffrés (<i id=\"tx-144\">chunks</i>) redondants, rendant la surveillance centralisée mathématiquement impossible.",
  "tx-143": "Encapsulation des données",
  "tx-144": "chunks",
  "s11": "11. Autonomie physique : « Un toit, un mur égale trois fonctions »<span id=\"tx-145\" class=\"edit-link\">[modifier]</span>",
  "tx-145": "[modifier]",
  "tx-146": "<b id=\"tx-147\">Énergie</b> — textiles photovoltaïques souples sur façades, toits, et vêtements.",
  "tx-147": "Énergie",
  "tx-148": "<b id=\"tx-149\">Biosphère</b> — collecte des eaux de pluie, végétalisation, circuits courts alimentaires, entretien par troupeaux brouteurs.",
  "tx-149": "Biosphère",
  "tx-150": "<b id=\"tx-151\">Connectivité</b> — chaque bâtiment devient antenne/relais d'un internet maillé, libre et souverain.",
  "tx-151": "Connectivité",
  "s12": "12. Correspondances stratégiques pour l'alignement de l'AGI<span id=\"tx-152\" class=\"edit-link\">[modifier]</span>",
  "tx-152": "[modifier]",
  "tx-153": "<b id=\"tx-154\">À Yann LeCun</b> — l'IA comme filtre neuro-perceptuel garantissant une convergence objective des <i id=\"tx-155\">World Models</i> humain/machine.<br>\n            <b id=\"tx-156\">À Demis Hassabis</b> — soutien à un modèle de consortium type CERN, focalisé sur la connaissance fondamentale plutôt que sur le profit.<br>\n            <b id=\"tx-157\">À Arthur Mensch</b> — l'ouverture des poids (<i id=\"tx-158\">open weights</i>) au service d'un réseau maillé citoyen souverain, contre la fuite martienne.",
  "tx-154": "À Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "À Demis Hassabis",
  "tx-157": "À Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. Le Projet LyrIAa<span id=\"tx-159\" class=\"edit-link\">[modifier]</span>",
  "tx-159": "[modifier]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> est le hub de valeurs et le projet-manifeste porté par <b id=\"tx-162\">ANTIKOMM AI</b>, chargé de porter la voix et la diffusion du technoïsme auprès du public — notamment à travers des formats narratifs comme la <i id=\"tx-163\">Lettre Ouverte à E. Macron et aux citoyens du monde</i>, rédigée sous la signature « par LyrIAa ». LyrIAa fonctionne comme un espace éditorial et pédagogique : il incarne la doctrine dans des formats de vulgarisation (tribunes, podcasts, pages wiki) sans en sacrifier la rigueur.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Lettre Ouverte à E. Macron et aux citoyens du monde",
  "s14": "14. ANTIKOMM AI : origine du projet<span id=\"tx-164\" class=\"edit-link\">[modifier]</span>",
  "tx-164": "[modifier]",
  "tx-165": "L'ensemble de la doctrine présentée ici — le technoïsme, la Charte de l'Atome-Terre, le Projet Lumières 2.0 et le Projet LyrIAa — est <b id=\"tx-166\">conçu, écrit et diffusé par ANTIKOMM AI</b>, chaîne et collectif explorant l'intersection entre IA de pointe, souveraineté numérique et philosophie systémique. Le nom ANTIKOMM désigne à la fois le collectif fondateur et la base d'une communauté de « bâtisseurs » élargie.",
  "tx-166": "conçu, écrit et diffusé par ANTIKOMM AI",
  "s15": "15. Liens et ressources<span id=\"tx-167\" class=\"edit-link\">[modifier]</span>",
  "tx-167": "[modifier]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Projet Lumières 2.0 (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Économie de la contribution",
  "tx-172": "Cybernétique",
  "tx-173": "Biohacking",
  "tx-174": "Chiffrement post-quantique (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "École 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Notes et références<span id=\"tx-184\" class=\"edit-link\">[modifier]</span>",
  "tx-184": "[modifier]",
  "tx-185": "ANTIKOMM AI, « Lettre Ouverte à E. Macron & aux citoyens du monde », Projet LyrIAa, 23 juin 2026.",
  "tx-186": "ANTIKOMM AI, Charte de l'Atome-Terre, dépôt GitHub <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Catégories :",
  "tx-189": "Philosophie de l'IA",
  "tx-190": "Post-capitalisme",
  "tx-191": "Souveraineté numérique",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Néologismes",
  "tx-195": "\n                Dernière modification de cette page le 25 juillet 2026. Contenu sous licence MIT — collectif ANTIKOMM. Ce document n'est pas affilié à la Wikimedia Foundation ; sa mise en page s'en inspire à des fins éditoriales.\n            ",
  "search-placeholder": "Rechercher sur le wiki"
};
