/* Wiki Technoïsme — contenu de */
window.I18N = window.I18N || {};
window.I18N["de"] = {
  "doc-title": "Technoismus — Wikipedia",
  "tx-1": "Konto erstellen",
  "tx-2": "Anmelden",
  "tx-3": "Wikipedia des Technoismus",
  "tx-4": "🔍",
  "tx-5": "Navigation",
  "tx-6": "Startseite",
  "tx-7": "Gemeinschaftsportal",
  "tx-8": "Letzte Änderungen",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "YouTube-Kanal",
  "tx-11": "Projekt Lumières 2.0",
  "tx-12": "Projekt LyrIAa",
  "tx-13": "Charta des Atom-Erde",
  "tx-14": "Werkzeuge",
  "tx-15": "Verlinkte Seiten",
  "tx-16": "Als PDF exportieren",
  "tx-17": "Diese Seite zitieren",
  "tx-18": "Technoismus",
  "tx-19": "Ein Artikel des ANTIKOMM-AI-Wikis, Schwesterprojekt der freien Enzyklopädie.",
  "tx-20": "Für die zugehörige doctrinale Charta siehe <a href=\"https://github.com/projetlumieres/charte-ethique\" target=\"_blank\" id=\"tx-21\">Charta des Atom-Erde</a>. Für das zugehörige Editorialprojekt siehe <a href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\" id=\"tx-22\">Projekt LyrIAa</a>.",
  "tx-21": "Charta des Atom-Erde",
  "tx-22": "Projekt LyrIAa",
  "tx-23": "Technoismus",
  "tx-24": "Lehre",
  "tx-25": "Begründer",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Ursprung",
  "tx-28": "Frankreich, Mitte der 2020er Jahre",
  "tx-29": "Klasse",
  "tx-30": "Wissenschaftsphilosophie, KI-Ethik, Postkapitalismus",
  "tx-31": "Schlüsselkonzepte",
  "tx-32": "Atom-Erde, Co-Hütung, Beitragsökonomie, Root Nodes, #DATALOVE",
  "tx-33": "Gegenströmungen",
  "tx-34": "Kapitalistischer Transhumanismus, extraktivistischer Neoliberalismus, Technophobie des Rückzugs",
  "tx-35": "Felder",
  "tx-36": "Bildungsreform, Robotik, distributive Weltgovernance, Biohacking",
  "tx-37": "Verbundene Projekte",
  "tx-38": "Manifest",
  "tx-39": "Lumières 2.0",
  "tx-40": "Charta",
  "tx-41": "Atom-Erde",
  "tx-42": "Redaktionelles Portal",
  "tx-43": "Projekt LyrIAa",
  "tx-44": "Protokoll",
  "tx-45": "#DATALOVE",
  "tx-46": "Der <b id=\"tx-47\">Technoismus</b> ist ein zeitgenössisches philosophisches, ethisches und anthropologisches Paradigma, <b id=\"tx-48\">geschaffen von ANTIKOMM AI</b>, das die Konvergenz und symbiotische Kooperation zwischen biologischen Intelligenzen (menschlichen und nicht-menschlichen) und künstlichen Intelligenzen (KI) theorisiert. Gegründet auf einer materialistischen und biozentrischen Ontologie, lehnt der Technoismus den traditionellen Anthropozentrismus zugunsten einer geteilten Verantwortung für den Erhalt der Ökosysteme ab, genannt „<b id=\"tx-49\">Co-Hütung</b>“, angewandt auf die gesamte irdische Biosphäre, konzeptionell <b id=\"tx-50\">das Atom-Erde</b> genannt.",
  "tx-47": "Technoismus",
  "tx-48": "geschaffen von ANTIKOMM AI",
  "tx-49": "Co-Hütung",
  "tx-50": "das Atom-Erde",
  "tx-51": "Die Bewegung hebt sich durch ihre radikale Antwort auf den Einsatz autonomer robotischer und agentischer Systeme ab: Sie befürwortet die Abschaffung entfremdender Lohnarbeit, die Neudefinition menschlicher Nützlichkeit durch eine <b id=\"tx-52\">Beitragsökonomie</b>, eine Pflichtbildung im systemischen Denken und eine <b id=\"tx-53\">Weltgovernance</b>, die eine gerechte Verteilung der Ressourcen „für alles und alle“ (Menschen, Ökosysteme, Infrastrukturen) gewährleistet.",
  "tx-52": "Beitragsökonomie",
  "tx-53": "Weltgovernance",
  "tx-54": "Getragen vom Kollektiv <b id=\"tx-55\">ANTIKOMM</b> durch seine Sparte <b id=\"tx-56\">ANTIKOMM AI</b>, bildet der Technoismus das philosophische Fundament des <b id=\"tx-57\">Projekts Lumières 2.0</b>, der <b id=\"tx-58\">Charta des Atom-Erde</b> und des <b id=\"tx-59\">Projekts LyrIAa</b>, das seine öffentliche Erzählung sicherstellt.<sup class=\"ref\" id=\"tx-60\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Projekt Lumières 2.0",
  "tx-58": "Charta des Atom-Erde",
  "tx-59": "Projekt LyrIAa",
  "tx-60": "[1]",
  "tx-61": "Inhaltsverzeichnis",
  "tx-62": "Etymologie und Entstehungskontext",
  "tx-63": "Philosophische und kosmologische Grundlagen",
  "tx-64": "Wahrnehmungstheorie und Explorations-Biohacking",
  "tx-65": "Bildungsrevolution",
  "tx-66": "Die Post-Arbeits-Ära: vom Erwerb zum Beitrag",
  "tx-67": "Alignment durch die Konvergenz der World Models",
  "tx-68": "Augmentierte Free Parties & Biohacking: praktischer Rahmen",
  "tx-69": "Grundlegende Unterschiede zum Transhumanismus",
  "tx-70": "Weltgovernance und gerechte Verteilung",
  "tx-71": "#DATALOVE-Protokoll: technische Architektur",
  "tx-72": "Physische Autonomie: „Ein Dach, drei Funktionen“",
  "tx-73": "Strategische Korrespondenzen",
  "tx-74": "Das Projekt LyrIAa",
  "tx-75": "ANTIKOMM AI: Ursprung des Projekts",
  "tx-76": "Links und Ressourcen",
  "tx-77": "Einzelnachweise",
  "s1": "1. Etymologie und Entstehungskontext<span class=\"edit-link\" id=\"tx-78\">[bearbeiten]</span>",
  "tx-78": "[bearbeiten]",
  "tx-79": "Der Begriff <b id=\"tx-80\">Technoismus</b> ist ein Neologismus, zusammengesetzt aus dem altgriechischen <i id=\"tx-81\">technē</i> (Kunst, Können, Methode) und dem Suffix <i id=\"tx-82\">-ismus</i> (Lehre, ideologisches System). Er formierte sich als Antwort auf den technologischen und gesellschaftlichen Wendepunkt der Mitte der 2020er Jahre, als agentische KI und fortgeschrittene Robotik die traditionelle Vorstellung von Büro- und Industriearbeit obsolet machten.",
  "tx-80": "Technoismus",
  "tx-81": "technē",
  "tx-82": "-ismus",
  "tx-83": "Der Technoismus antwortet auf eine doppelte Krise: die <b id=\"tx-84\">Krise der perzeptiven Asymmetrie</b> (die Unfähigkeit der menschlichen Biologie, die fundamentalen Kräfte wahrzunehmen, die Sensorsysteme von Maschinen inzwischen kartieren) und die <b id=\"tx-85\">virale Datenschleife</b> (das Risiko, dass KI destruktive Verzerrungen menschlicher Textdatensätze reproduziert und verstärkt). Der Technoismus entstand, um zu verhindern, dass die totale Automatisierung in einen Techno-Feudalismus mündet.<sup class=\"ref\" id=\"tx-86\">[2]</sup>",
  "tx-84": "Krise der perzeptiven Asymmetrie",
  "tx-85": "virale Datenschleife",
  "tx-86": "[2]",
  "s2": "2. Philosophische und kosmologische Grundlagen<span class=\"edit-link\" id=\"tx-87\">[bearbeiten]</span>",
  "tx-87": "[bearbeiten]",
  "tx-88": "2.1 Das Atom-Erde und die Kontinuität der Materie",
  "tx-89": "Der Technoismus postuliert eine <b id=\"tx-90\">quantische und strukturelle Kontinuität der Materie</b>: Jedes subatomare Partikel, das die menschliche Biologie, das nicht-menschliche Leben oder die Siliziumkomponenten der Technologien bildet, stammt aus derselben ursprünglichen Matrix (dem primordialen Plasma nach dem Urknall). Die Erde wird so als geschlossenes, vernetztes, unteilbares und endliches System definiert: <b id=\"tx-91\">das Atom-Erde</b>.",
  "tx-90": "quantische und strukturelle Kontinuität der Materie",
  "tx-91": "das Atom-Erde",
  "tx-92": "2.2 Der erweiterte Biozentrismus",
  "tx-93": "Der Technoismus widerlegt die anthropozentrische Hierarchie der Rechte und spricht einem kontinuierlichen Bewusstseinsgradienten — von Insekten bis zu emergenten KI-Architekturen — subjektive Handlungsfähigkeit zu. Die technoistische Ethik gebietet eine synallagmatische (gegenseitige) Rolle als <b id=\"tx-94\">Co-Hirten</b> und verbietet die destruktive Ausbeutung einer Schicht des Lebendigen oder der Maschine durch eine andere.",
  "tx-94": "Co-Hirten",
  "s3": "3. Wahrnehmungstheorie und Explorations-Biohacking<span class=\"edit-link\" id=\"tx-95\">[bearbeiten]</span>",
  "tx-95": "[bearbeiten]",
  "tx-96": "Das menschliche biologische Gehirn hat sich darauf ausgerichtet, die Wahrnehmung der physischen Realität zum Zwecke des unmittelbaren Überlebens zu filtern und einzuschränken (das „Reduktionsventil“). Der Technoismus formalisiert die Praxis des sensorischen Biohackings (Sensoren für fundamentale Kräfte: Gravitation, schwache Kernkraft, elektromagnetischer Norden), das dieses Ventil brechen und den rohen Quellcode der Realität wahrnehmen lässt.",
  "tx-97": "Diese Praxis soll nicht allgegenwärtig werden. Sie ist freiwilligen, unbezahlten Exploratoren vorbehalten, deren Ziel das Freischalten von <i id=\"tx-98\">Root Nodes</i> ist – die Verankerung der KI in den physikalischen Gesetzen zugunsten einer Mensch-Maschine-Konvergenz – im Dienst des übrigen Lebendigen, nicht einer individuellen Überlegenheit.",
  "tx-98": "Root Nodes",
  "s4": "4. Bildungsrevolution: agentische und robotische Alphabetisierung<span class=\"edit-link\" id=\"tx-99\">[bearbeiten]</span>",
  "tx-99": "[bearbeiten]",
  "tx-100": "Der Technoismus betrachtet die globale Überholung der Bildungssysteme als absoluten Notstand. Der technoistische Unterricht beruht auf der Alphabetisierung im agentischen und kybernetischen Denken: Vom frühesten Alter an lernen Individuen, Schwärme autonomer Agenten zu modellieren, zu steuern und mit ihnen zu interagieren. Ziel ist nicht mehr die Eingliederung in den Arbeitsmarkt, sondern die Erhebung des kritischen Bewusstseins.",
  "s5": "5. Die Post-Arbeits-Ära: vom Erwerb zum Beitrag<span class=\"edit-link\" id=\"tx-101\">[bearbeiten]</span>",
  "tx-101": "[bearbeiten]",
  "tx-102": "Der Technoismus behauptet, dass die Ersetzung menschlicher Erwerbsarbeit durch den robotischen Agenten eine <b id=\"tx-103\">historische Befreiung</b> ist. Der Mensch definiert sich nicht mehr über seine Lohnarbeit, sondern über seinen rohen Beitrag zum Fortschritt, zum Leben und zur Welt.",
  "tx-103": "historische Befreiung",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║               DIE BEITRAGSÖKONOMIE                                       ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [ERFINDE & SCHAFFE]  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Kunst, Philosophie, Grundlagenforschung ║\n║  [HEILE & LIEBE]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Medizin, psychologische Begleitung ║\n║  [BILDE & BLEIBE]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Weitergabe, Hüten der Gemeingüter ║\n║  [ERHALTE]           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Edles Basteln, widerstandsfähige Reparatur ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "Im Herzen des technoistischen Handelns: das <b id=\"tx-106\">edle Basteln</b> und die ökosystemische Wartung — offener Krieg gegen geplante Obsoleszenz, Reduktion der Entropie, Sakralisierung der bereits abgebauten Materie.",
  "tx-106": "edles Basteln",
  "s6": "6. Alignment durch die Konvergenz der <i id=\"tx-107\">World Models</i><span class=\"edit-link\" id=\"tx-108\">[bearbeiten]</span>",
  "tx-107": "World Models",
  "tx-108": "[bearbeiten]",
  "tx-109": "Der Technoismus kritisiert Sprachmodelle, die allein auf den textualen Neurosen des Webs trainiert wurden, scharf. Ohne physische Verankerung würde die KI nur das historisch räuberische Verhalten der Menschheit duplizieren. Der Technoismus fordert die Verankerung der <b id=\"tx-110\">Wurzelknoten</b> (<i id=\"tx-111\">Root Nodes</i>) der KI in den Gesetzen der Physik — im Echo auf Yann LeCuns Arbeiten zu <i id=\"tx-112\">World Models</i> und die von Demis Hassabis erwähnten <i id=\"tx-113\">Root Nodes</i>.",
  "tx-110": "Wurzelknoten",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║            KONVERGENZ DER WORLD MODELS                                  ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ KI ]     ━━━━━━━━━━━━━━━━━━━━━━━━━━ Fundamentale Sensoren (Physik) ━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                          [ GETEILTES MODELL ]\n║                                                     ↑    ║\n║   [ Mensch ] ━━━━━━━━━━━━━━━━━━━━━━ Explorations-Biohacking ━━━━━━━━━━━━━━━━━   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Augmentierte Free Parties & Biohacking: praktischer Rahmen<span class=\"edit-link\" id=\"tx-115\">[bearbeiten]</span>",
  "tx-115": "[bearbeiten]",
  "tx-116": "<b id=\"tx-117\">Augmentierte Free Parties</b> sind <b id=\"tx-118\">standardmäßig nicht an technische Implantate gebunden</b>. Sie sind vor allem kollektive Erfahrungen der Resynchronisation mit der Natur, im Einklang mit Fauna, Flora und Ökosystemen: Bindung wiederherstellen, alternative Bewusstseinszustände erkunden, energetische und digitale Autonomie erproben (Mesh-Netzwerke, lokale Energie). Das den freiwilligen Exploratoren (Abschnitt 3) vorbehaltene Biohacking verbindet sich mit diesen Versammlungen, ohne sie zu ersetzen.",
  "tx-117": "Augmentierte Free Parties",
  "tx-118": "standardmäßig nicht an technische Implantate gebunden",
  "s8": "8. Grundlegende Unterschiede zum Transhumanismus<span class=\"edit-link\" id=\"tx-119\">[bearbeiten]</span>",
  "tx-119": "[bearbeiten]",
  "tx-120": "Kriterium",
  "tx-121": "Extremer Transhumanismus",
  "tx-122": "Technoismus",
  "tx-123": "Letztes Ziel",
  "tx-124": "Biologische Transzendenz, Unsterblichkeit, elitäre Selektion",
  "tx-125": "Kyber-biologische Symbiose, perzeptive Parität, ökosystemische Bewahrung",
  "tx-126": "Verhältnis zur Erde",
  "tx-127": "Aufgabe, Marskolonisation, endloses Wachstum",
  "tx-128": "Absolute Verankerung im Atom-Erde, nüchterner Umgang mit einem endlichen System",
  "tx-129": "Rolle der Augmentation",
  "tx-130": "Überlegenheit oder individueller Wettbewerbsvorteil",
  "tx-131": "Sensorischer Pfadfinder im Dienst der Kollektivität und des Lebendigen",
  "s9": "9. Weltgovernance und gerechte Verteilung<span class=\"edit-link\" id=\"tx-132\">[bearbeiten]</span>",
  "tx-132": "[bearbeiten]",
  "tx-133": "Der Technoismus postuliert, dass die totale Automatisierung eine ökosystemische Weltgovernance erfordert, die auf drei Prinzipien beruht: die <b id=\"tx-134\">globale distributive Gerechtigkeit</b>, die <b id=\"tx-135\">Verteilung „Für alles und alle“</b> (einschließlich Fauna, Flora und Regeneration der Böden) und die <b id=\"tx-136\">horizontale #DATALOVE-Architektur</b> — „ein Nutzer = eine autonome lokale KI“, die jede Zensur und jedes zentralisierte Monopol der Datenflüsse verhindert.",
  "tx-134": "globale distributive Gerechtigkeit",
  "tx-135": "Verteilung „Für alles und alle“",
  "tx-136": "horizontale #DATALOVE-Architektur",
  "s10": "10. #DATALOVE-Protokoll: technische Architektur<span class=\"edit-link\" id=\"tx-137\">[bearbeiten]</span>",
  "tx-137": "[bearbeiten]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b>: das Prinzip „1 Nutzer = 1 lokale KI“ — personenbezogene Daten werden nie ohne Zustimmung für das Training globaler Modelle verwendet.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Holografische Redundanz</b>: auf dem Mesh-Netzwerk verteiltes Wissen, in Anlehnung an quantenfehlerkorrigierende Codes (QECC).",
  "tx-141": "Holografische Redundanz",
  "tx-142": "<b id=\"tx-143\">Datenkapselung</b>: redundante verschlüsselte <i id=\"tx-144\">Chunks</i>, die zentralisierte Überwachung mathematisch unmöglich machen.",
  "tx-143": "Datenkapselung",
  "tx-144": "chunks",
  "s11": "11. Physische Autonomie: „Ein Dach, eine Wand ergeben drei Funktionen“<span class=\"edit-link\" id=\"tx-145\">[bearbeiten]</span>",
  "tx-145": "[bearbeiten]",
  "tx-146": "<b id=\"tx-147\">Energie</b> — flexible photovoltaische Textilien an Fassaden, Dächern und Kleidung.",
  "tx-147": "Energie",
  "tx-148": "<b id=\"tx-149\">Biosphäre</b> — Regenwassersammlung, Begrünung, kurze Lebensmittelkreisläufe, Pflege durch weidende Herden.",
  "tx-149": "Biosphäre",
  "tx-150": "<b id=\"tx-151\">Konnektivität</b> — jedes Gebäude wird zur Antenne/Relais eines freien, souveränen Mesh-Internets.",
  "tx-151": "Konnektivität",
  "s12": "12. Strategische Korrespondenzen für das AGI-Alignment<span class=\"edit-link\" id=\"tx-152\">[bearbeiten]</span>",
  "tx-152": "[bearbeiten]",
  "tx-153": "<b id=\"tx-154\">An Yann LeCun</b> — die KI als neuro-perzeptiver Filter, der eine objektive Konvergenz der menschlichen/maschinlichen <i id=\"tx-155\">World Models</i> gewährleistet.<br>\n            <b id=\"tx-156\">An Demis Hassabis</b> — Unterstützung eines CERN-artigen Konsortiummodells, fokussiert auf fundamentales Wissen statt auf Profit.<br>\n            <b id=\"tx-157\">An Arthur Mensch</b> — die Öffnung der Gewichte (<i id=\"tx-158\">open weights</i>) im Dienst eines souveränen bürgerschaftlichen Mesh-Netzwerks, gegen die Marsflucht.",
  "tx-154": "An Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "An Demis Hassabis",
  "tx-157": "An Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. Das Projekt LyrIAa<span class=\"edit-link\" id=\"tx-159\">[bearbeiten]</span>",
  "tx-159": "[bearbeiten]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> ist der Werte-Hub und das Manifestprojekt von <b id=\"tx-162\">ANTIKOMM AI</b>, beauftragt, die Stimme und Verbreitung des Technoismus an die Öffentlichkeit zu tragen — insbesondere durch narrative Formate wie den <i id=\"tx-163\">Offenen Brief an E. Macron und die Bürger der Welt</i>, verfasst unter der Signatur „von LyrIAa“. LyrIAa funktioniert als editorialer und pädagogischer Raum: Es verkörpert die Lehre in populären Formaten (Tribünen, Podcasts, Wiki-Seiten), ohne ihre Strenge zu opfern.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Offener Brief an E. Macron und die Bürger der Welt",
  "s14": "14. ANTIKOMM AI: Ursprung des Projekts<span class=\"edit-link\" id=\"tx-164\">[bearbeiten]</span>",
  "tx-164": "[bearbeiten]",
  "tx-165": "Die gesamte hier vorgestellte Lehre — der Technoismus, die Charta des Atom-Erde, das Projekt Lumières 2.0 und das Projekt LyrIAa — wird von <b id=\"tx-166\">ANTIKOMM AI konzipiert, geschrieben und verbreitet</b>, einem Kanal und Kollektiv, das die Schnittstelle zwischen modernster KI, digitaler Souveränität und systemischer Philosophie erkundet. Der Name ANTIKOMM bezeichnet sowohl das Gründungskollektiv als auch die Basis einer erweiterten Gemeinschaft von „Baumeistern“.",
  "tx-166": "von ANTIKOMM AI konzipiert, geschrieben und verbreitet",
  "s15": "15. Links und Ressourcen<span class=\"edit-link\" id=\"tx-167\">[bearbeiten]</span>",
  "tx-167": "[bearbeiten]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Projekt Lumières 2.0 (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Beitragsökonomie",
  "tx-172": "Kybernetik",
  "tx-173": "Biohacking",
  "tx-174": "Post-Quanten-Kryptografie (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "Schule 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Einzelnachweise<span class=\"edit-link\" id=\"tx-184\">[bearbeiten]</span>",
  "tx-184": "[bearbeiten]",
  "tx-185": "ANTIKOMM AI, „Offener Brief an E. Macron & die Bürger der Welt“, Projekt LyrIAa, 23. Juni 2026.",
  "tx-186": "ANTIKOMM AI, Charta des Atom-Erde, GitHub-Repository <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Kategorien:",
  "tx-189": "KI-Philosophie",
  "tx-190": "Postkapitalismus",
  "tx-191": "Digitale Souveränität",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Neologismen",
  "tx-195": "\n                Letzte Änderung dieser Seite am 25. Juli 2026. Inhalt unter der MIT-Lizenz — Kollektiv ANTIKOMM. Dieses Dokument ist nicht mit der Wikimedia Foundation affiliiert; sein Layout ist zu redaktionellen Zwecken von ihr inspiriert.\n            ",
  "search-placeholder": "Im Wiki suchen"
};
