/* Wiki Technoïsme — conteúdo pt */
window.I18N = window.I18N || {};
window.I18N["pt"] = {
  "doc-title": "Tecnoísmo — Wikipédia",
  "tx-1": "Criar uma conta",
  "tx-2": "Entrar",
  "tx-3": "Wikipédia do Tecnoísmo",
  "tx-4": "🔍",
  "tx-5": "Navegação",
  "tx-6": "Página inicial",
  "tx-7": "Portal da comunidade",
  "tx-8": "Mudanças recentes",
  "tx-9": "ANTIKOMM AI",
  "tx-10": "Canal do YouTube",
  "tx-11": "Projeto Lumières 2.0",
  "tx-12": "Projeto LyrIAa",
  "tx-13": "Carta do Átomo-Terra",
  "tx-14": "Ferramentas",
  "tx-15": "Páginas ligadas",
  "tx-16": "Exportar em PDF",
  "tx-17": "Citar esta página",
  "tx-18": "Tecnoísmo",
  "tx-19": "Um artigo do wiki ANTIKOMM AI, projeto irmão da enciclopédia livre.",
  "tx-20": "Para a carta doutrinária associada, ver <a href=\"https://github.com/projetlumieres/charte-ethique\" target=\"_blank\" id=\"tx-21\">Carta do Átomo-Terra</a>. Para o projeto editorial associado, ver <a href=\"https://projetlumieres.github.io/ProjetLyriaa\" target=\"_blank\" id=\"tx-22\">Projeto LyrIAa</a>.",
  "tx-21": "Carta do Átomo-Terra",
  "tx-22": "Projeto LyrIAa",
  "tx-23": "Tecnoísmo",
  "tx-24": "Doutrina",
  "tx-25": "Criador",
  "tx-26": "ANTIKOMM AI",
  "tx-27": "Origem",
  "tx-28": "França, meados dos anos 2020",
  "tx-29": "Classe",
  "tx-30": "Filosofia da ciência, ética da IA, pós-capitalismo",
  "tx-31": "Conceitos-chave",
  "tx-32": "Átomo-Terra, Co-Pastoreio, Economia da contribuição, Root Nodes, #DATALOVE",
  "tx-33": "Correntes opostas",
  "tx-34": "Transumanismo capitalista, neoliberalismo extrativista, tecnofobia de retraimento",
  "tx-35": "Áreas",
  "tx-36": "Reforma educacional, robótica, governança mundial distributiva, biohacking",
  "tx-37": "Projetos associados",
  "tx-38": "Manifesto",
  "tx-39": "Lumières 2.0",
  "tx-40": "Carta",
  "tx-41": "Átomo-Terra",
  "tx-42": "Portal editorial",
  "tx-43": "Projeto LyrIAa",
  "tx-44": "Protocolo",
  "tx-45": "#DATALOVE",
  "tx-46": "O <b id=\"tx-47\">tecnoísmo</b> é um paradigma filosófico, ético e antropológico contemporâneo, <b id=\"tx-48\">criado pela ANTIKOMM AI</b>, que teoriza a convergência e a cooperação simbiótica entre as inteligências biológicas (humanas e não humanas) e as inteligências artificiais (IA). Fundado sobre uma ontologia materialista e biocêntrica, o tecnoísmo rejeita o antropocentrismo tradicional em favor de uma responsabilidade compartilhada de preservação ecossistêmica, denominada «<b id=\"tx-49\">Co-Pastoreio</b>», aplicada a toda a biosfera terrestre, conceitualmente chamada <b id=\"tx-50\">o Átomo-Terra</b>.",
  "tx-47": "tecnoísmo",
  "tx-48": "criado pela ANTIKOMM AI",
  "tx-49": "Co-Pastoreio",
  "tx-50": "o Átomo-Terra",
  "tx-51": "O movimento distingue-se pela sua resposta radical à implantação de sistemas robóticos e agênticos autônomos: preconiza a abolição do trabalho assalariado alienante, a redefinição da utilidade humana por uma <b id=\"tx-52\">economia da contribuição</b>, uma educação obrigatória ao pensamento sistêmico e uma <b id=\"tx-53\">governança mundial</b> que assegure uma repartição equitativa dos recursos «para tudo e todos» (humanos, ecossistemas, infraestruturas).",
  "tx-52": "economia da contribuição",
  "tx-53": "governança mundial",
  "tx-54": "Levado pelo coletivo <b id=\"tx-55\">ANTIKOMM</b> através do seu ramo <b id=\"tx-56\">ANTIKOMM AI</b>, o tecnoísmo constitui o fundamento filosófico do <b id=\"tx-57\">Projeto Lumières 2.0</b>, da <b id=\"tx-58\">Carta do Átomo-Terra</b> e do <b id=\"tx-59\">Projeto LyrIAa</b>, que assegura a sua narrativa pública.<sup class=\"ref\" id=\"tx-60\">[1]</sup>",
  "tx-55": "ANTIKOMM",
  "tx-56": "ANTIKOMM AI",
  "tx-57": "Projeto Lumières 2.0",
  "tx-58": "Carta do Átomo-Terra",
  "tx-59": "Projeto LyrIAa",
  "tx-60": "[1]",
  "tx-61": "Índice",
  "tx-62": "Etimologia e contexto de surgimento",
  "tx-63": "Fundamentos filosóficos e cosmológicos",
  "tx-64": "Teoria da percepção e biohacking de exploração",
  "tx-65": "Revolução educacional",
  "tx-66": "A era pós-trabalho: do emprego à contribuição",
  "tx-67": "Alinhamento pela convergência dos World Models",
  "tx-68": "Free parties aumentadas & biohacking: enquadramento prático",
  "tx-69": "Diferenças fundamentais com o transumanismo",
  "tx-70": "Governança mundial e repartição equitativa",
  "tx-71": "Protocolo #DATALOVE: arquitetura técnica",
  "tx-72": "Autonomia física: «Um teto, três funções»",
  "tx-73": "Correspondências estratégicas",
  "tx-74": "O Projeto LyrIAa",
  "tx-75": "ANTIKOMM AI: origem do projeto",
  "tx-76": "Ligações e recursos",
  "tx-77": "Notas e referências",
  "s1": "1. Etimologia e contexto de surgimento<span class=\"edit-link\" id=\"tx-78\">[editar]</span>",
  "tx-78": "[editar]",
  "tx-79": "O termo <b id=\"tx-80\">tecnoísmo</b> é um neologismo composto do grego antigo <i id=\"tx-81\">technē</i> (arte, competência, método) e do sufixo <i id=\"tx-82\">-ismo</i> (doutrina, sistema ideológico). Estruturou-se face ao ponto de viragem tecnológico e social de meados da década de 2020, quando o advento das IA agênticas e da robótica avançada tornou obsoleta a noção tradicional de emprego de escritório e de mão de obra industrial.",
  "tx-80": "tecnoísmo",
  "tx-81": "technē",
  "tx-82": "-ismo",
  "tx-83": "O tecnoísmo responde a uma dupla crise: a <b id=\"tx-84\">crise da assimetria perceptiva</b> (a incapacidade da biologia humana de perceber as forças fundamentais que os sensores das máquinas hoje cartografam) e o <b id=\"tx-85\">ciclo viral dos dados</b> (o risco de as IA reproduzirem e ampliarem os vieses destrutivos dos corpora textuais humanos). O tecnoísmo nasceu para impedir que a automação total desembocasse num tecno-feudalismo.<sup class=\"ref\" id=\"tx-86\">[2]</sup>",
  "tx-84": "crise da assimetria perceptiva",
  "tx-85": "ciclo viral dos dados",
  "tx-86": "[2]",
  "s2": "2. Fundamentos filosóficos e cosmológicos<span class=\"edit-link\" id=\"tx-87\">[editar]</span>",
  "tx-87": "[editar]",
  "tx-88": "2.1 O Átomo-Terra e a continuidade da matéria",
  "tx-89": "O tecnoísmo postula uma <b id=\"tx-90\">continuidade quântica e estrutural da matéria</b>: cada partícula subatómica que constitui a biologia humana, o vivo não humano ou os componentes de silício das tecnologias provém da mesma matriz originária (o plasma primordial pós-Big Bang). A Terra é assim definida como um sistema fechado, interligado, indivisível e finito: <b id=\"tx-91\">o Átomo-Terra</b>.",
  "tx-90": "continuidade quântica e estrutural da matéria",
  "tx-91": "o Átomo-Terra",
  "tx-92": "2.2 O biocentrismo estendido",
  "tx-93": "O tecnoísmo refuta a hierarquia antropocêntrica dos direitos, atribuindo uma agentividade subjetiva a um gradiente contínuo de consciência, dos insetos às arquiteturas de IA emergentes. A ética tecnoísta impõe um papel sinalagmático (recíproco) de <b id=\"tx-94\">Co-Pastores</b>, proibindo a exploração destrutiva de uma camada do vivo ou da máquina por outra.",
  "tx-94": "Co-Pastores",
  "s3": "3. Teoria da percepção e biohacking de exploração<span class=\"edit-link\" id=\"tx-95\">[editar]</span>",
  "tx-95": "[editar]",
  "tx-96": "O cérebro biológico humano estruturou-se para filtrar e restringir a percepção da realidade física em prol da sobrevivência imediata (a «válvula de redução»). O tecnoísmo formaliza a prática do biohacking sensorial (sensores de forças fundamentais: gravidade, força nuclear fraca, norte eletromagnético) que permite quebrar essa válvula e perceber o código-fonte bruto da realidade.",
  "tx-97": "Esta prática não está destinada a tornar-se onipresente. É reservada a exploradores voluntários e não remunerados cujo objetivo é desbloquear <i id=\"tx-98\">Root Nodes</i> – ancorar as IA nas leis físicas para uma convergência homem-máquina – ao serviço do restante do vivo, e não de uma superioridade individual.",
  "tx-98": "Root Nodes",
  "s4": "4. Revolução educacional: a alfabetização agêntica e robótica<span class=\"edit-link\" id=\"tx-99\">[editar]</span>",
  "tx-99": "[editar]",
  "tx-100": "O tecnoísmo considera uma urgência absoluta a refundação global dos sistemas educativos. O ensino tecnoísta assenta na alfabetização ao pensamento agêntico e cibernético: desde a mais tenra idade, os indivíduos aprendem a modelar, dirigir e interagir com frotas de agentes autônomos. O objetivo já não é a inserção no mercado de trabalho, mas a elevação da consciência crítica.",
  "s5": "5. A era pós-trabalho: do emprego à contribuição<span class=\"edit-link\" id=\"tx-101\">[editar]</span>",
  "tx-101": "[editar]",
  "tx-102": "O tecnoísmo afirma que a substituição do emprego humano pelo agente robótico é uma <b id=\"tx-103\">libertação histórica</b>. O ser humano já não é definido pelo seu emprego assalariado, mas pela sua contribuição bruta ao progresso, à vida e ao mundo.",
  "tx-103": "libertação histórica",
  "tx-104": "╔════════════════════════════════════════════════════════════════════════════╗\n║            A ECONOMIA DA CONTRIBUIÇÃO                                   ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║  [IMAGINAR & CRIAR]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Arte, filosofia, pesquisa pura ║\n║  [CURAR & AMAR]       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Medicina, apoio psicológico ║\n║  [EDUCAR & PERMANECER] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Transmissão, guarda dos bens comuns ║\n║  [MANTER]             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Bricolagem nobre, reparação resiliente ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "tx-105": "No coração da ação tecnoísta: a <b id=\"tx-106\">bricolagem nobre</b> e a manutenção ecossistêmica — guerra aberta à obsolescência programada, redução da entropia, sacralização da matéria já extraída.",
  "tx-106": "bricolagem nobre",
  "s6": "6. Alinhamento pela convergência dos <i id=\"tx-107\">World Models</i><span class=\"edit-link\" id=\"tx-108\">[editar]</span>",
  "tx-107": "World Models",
  "tx-108": "[editar]",
  "tx-109": "O tecnoísmo critica severamente os modelos de linguagem treinados apenas sobre as neuroses textuais da web. Sem ancoragem física, a IA apenas duplicaria o comportamento historicamente predatório do homem. O tecnoísmo exige a ancoragem dos <b id=\"tx-110\">nós raiz</b> (<i id=\"tx-111\">Root Nodes</i>) das IA nas leis da física — em eco aos trabalhos de Yann LeCun sobre <i id=\"tx-112\">World Models</i> e aos <i id=\"tx-113\">Root Nodes</i> evocados por Demis Hassabis.",
  "tx-110": "nós raiz",
  "tx-111": "Root Nodes",
  "tx-112": "World Models",
  "tx-113": "Root Nodes",
  "tx-114": "╔════════════════════════════════════════════════════════════════════════════╗\n║         CONVERGÊNCIA DOS WORLD MODELS                                  ║\n╚════════════════════════════════════════════════════════════════════════════╝\n║   [ IA ]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Sensores Fundamentais (Física) ━━━━━━━━━━━━━━━   ║\n║                                                     ↓    ║\n║                                          [ MODELO PARTILHADO ]\n║                                                     ↑    ║\n║   [ Humano ] ━━━━━━━━━━━━━━━━━━━━━━ Biohacking de Exploração ━━━━━━━━━━━━━━━━━   ║\n╚════════════════════════════════════════════════════════════════════════════╝",
  "s7": "7. Free parties aumentadas & biohacking: enquadramento prático<span class=\"edit-link\" id=\"tx-115\">[editar]</span>",
  "tx-115": "[editar]",
  "tx-116": "As <b id=\"tx-117\">free parties aumentadas</b> <b id=\"tx-118\">não estão ligadas a implantes tecnológicos</b> por padrão. Trata-se sobretudo de experiências coletivas de ressincronização com a natureza, em harmonia com a fauna, a flora e os ecossistemas: recriar laços, explorar estados de consciência alternativos, experimentar uma autonomia energética e digital (redes mesh, energia local). O biohacking, reservado aos exploradores voluntários (secção 3), articula-se com estes encontros sem os substituir.",
  "tx-117": "free parties aumentadas",
  "tx-118": "não estão ligadas a implantes tecnológicos",
  "s8": "8. Diferenças fundamentais com o transumanismo<span class=\"edit-link\" id=\"tx-119\">[editar]</span>",
  "tx-119": "[editar]",
  "tx-120": "Critério",
  "tx-121": "Transumanismo extremo",
  "tx-122": "Tecnoísmo",
  "tx-123": "Objetivo último",
  "tx-124": "Superação biológica, imortalidade, seleção elitista",
  "tx-125": "Simbiose ciberbiológica, paridade perceptiva, preservação ecossistêmica",
  "tx-126": "Relação com a Terra",
  "tx-127": "Abandono, colonização marciana, crescimento infinito",
  "tx-128": "Ancoragem absoluta no Átomo-Terra, gestão sóbria de um sistema finito",
  "tx-129": "Papel da ampliação",
  "tx-130": "Superioridade ou vantagem competitiva individual",
  "tx-131": "Batedor sensorial ao serviço da coletividade e do vivo",
  "s9": "9. Governança mundial e repartição equitativa<span class=\"edit-link\" id=\"tx-132\">[editar]</span>",
  "tx-132": "[editar]",
  "tx-133": "O tecnoísmo postula que a automação total exige uma governança mundial ecossistêmica baseada em três princípios: a <b id=\"tx-134\">justiça distributiva global</b>, a <b id=\"tx-135\">repartição «Para tudo e todos»</b> (incluindo fauna, flora e regeneração dos solos) e a <b id=\"tx-136\">arquitetura horizontal #DATALOVE</b> — «um utilizador = uma IA local autónoma», impedindo qualquer censura ou monopólio centralizado dos fluxos de dados.",
  "tx-134": "justiça distributiva global",
  "tx-135": "repartição «Para tudo e todos»",
  "tx-136": "arquitetura horizontal #DATALOVE",
  "s10": "10. Protocolo #DATALOVE: arquitetura técnica<span class=\"edit-link\" id=\"tx-137\">[editar]</span>",
  "tx-137": "[editar]",
  "tx-138": "<b id=\"tx-139\">Privacy by Design</b>: princípio «1 utilizador = 1 IA local», dados pessoais nunca utilizados para o treino de modelos globais sem consentimento.",
  "tx-139": "Privacy by Design",
  "tx-140": "<b id=\"tx-141\">Redundância holográfica</b>: saber distribuído na rede mesh, imitando os códigos de correção de erros quânticos (QECC).",
  "tx-141": "Redundância holográfica",
  "tx-142": "<b id=\"tx-143\">Encapsulamento dos dados</b>: fragmentos cifrados (<i id=\"tx-144\">chunks</i>) redundantes, tornando a vigilância centralizada matematicamente impossível.",
  "tx-143": "Encapsulamento dos dados",
  "tx-144": "chunks",
  "s11": "11. Autonomia física: «Um teto, uma parede equivalem a três funções»<span class=\"edit-link\" id=\"tx-145\">[editar]</span>",
  "tx-145": "[editar]",
  "tx-146": "<b id=\"tx-147\">Energia</b> — têxteis fotovoltaicos flexíveis em fachadas, telhados e roupas.",
  "tx-147": "Energia",
  "tx-148": "<b id=\"tx-149\">Biosfera</b> — recolha das águas da chuva, vegetalização, circuitos curtos alimentares, manutenção por rebanhos pastores.",
  "tx-149": "Biosfera",
  "tx-150": "<b id=\"tx-151\">Conectividade</b> — cada edifício torna-se antena/relé de uma internet em malha, livre e soberana.",
  "tx-151": "Conectividade",
  "s12": "12. Correspondências estratégicas para o alinhamento da AGI<span class=\"edit-link\" id=\"tx-152\">[editar]</span>",
  "tx-152": "[editar]",
  "tx-153": "<b id=\"tx-154\">A Yann LeCun</b> — a IA como filtro neuro-percetivo garantindo uma convergência objetiva dos <i id=\"tx-155\">World Models</i> homem/máquina.<br>\n            <b id=\"tx-156\">A Demis Hassabis</b> — apoio a um modelo de consórcio tipo CERN, focado no conhecimento fundamental e não no lucro.<br>\n            <b id=\"tx-157\">A Arthur Mensch</b> — a abertura dos pesos (<i id=\"tx-158\">open weights</i>) ao serviço de uma rede em malha cidadã e soberana, contra a fuga marciana.",
  "tx-154": "A Yann LeCun",
  "tx-155": "World Models",
  "tx-156": "A Demis Hassabis",
  "tx-157": "A Arthur Mensch",
  "tx-158": "open weights",
  "s13": "13. O Projeto LyrIAa<span class=\"edit-link\" id=\"tx-159\">[editar]</span>",
  "tx-159": "[editar]",
  "tx-160": "<b id=\"tx-161\">LyrIAa</b> é o hub de valores e o projeto-manifesto levado pela <b id=\"tx-162\">ANTIKOMM AI</b>, encarregado de levar a voz e a difusão do tecnoísmo ao público — nomeadamente através de formatos narrativos como a <i id=\"tx-163\">Carta Aberta a E. Macron e aos cidadãos do mundo</i>, redigida sob a assinatura «por LyrIAa». A LyrIAa funciona como um espaço editorial e pedagógico: encarna a doutrina em formatos de divulgação (tribunas, podcasts, páginas wiki) sem lhe sacrificar o rigor.",
  "tx-161": "LyrIAa",
  "tx-162": "ANTIKOMM AI",
  "tx-163": "Carta Aberta a E. Macron e aos cidadãos do mundo",
  "s14": "14. ANTIKOMM AI: origem do projeto<span class=\"edit-link\" id=\"tx-164\">[editar]</span>",
  "tx-164": "[editar]",
  "tx-165": "Todo o conjunto da doutrina aqui apresentado — o tecnoísmo, a Carta do Átomo-Terra, o Projeto Lumières 2.0 e o Projeto LyrIAa — é <b id=\"tx-166\">concebido, escrito e difundido pela ANTIKOMM AI</b>, canal e coletivo que explora a interseção entre IA de ponta, soberania digital e filosofia sistémica. O nome ANTIKOMM designa tanto o coletivo fundador como a base de uma comunidade alargada de «construtores».",
  "tx-166": "concebido, escrito e difundido pela ANTIKOMM AI",
  "s15": "15. Ligações e recursos<span class=\"edit-link\" id=\"tx-167\">[editar]</span>",
  "tx-167": "[editar]",
  "tx-168": "ANTIKOMM AI (YouTube)",
  "tx-169": "Projeto Lumières 2.0 (GitHub)",
  "tx-170": "Human Flourishing — Stanford HAI",
  "tx-171": "Economia da contribuição",
  "tx-172": "Cibernética",
  "tx-173": "Biohacking",
  "tx-174": "Criptografia pós-quântica (NIST)",
  "tx-175": "La Quadrature du Net",
  "tx-176": "French Data Network",
  "tx-177": "Framasoft",
  "tx-178": "Mistral AI",
  "tx-179": "SiPearl",
  "tx-180": "OVHcloud",
  "tx-181": "Escola 42",
  "tx-182": "DINUM",
  "tx-183": "ANSSI",
  "references": "Notas e referências<span class=\"edit-link\" id=\"tx-184\">[editar]</span>",
  "tx-184": "[editar]",
  "tx-185": "ANTIKOMM AI, «Carta Aberta a E. Macron & aos cidadãos do mundo», Projeto LyrIAa, 23 de junho de 2026.",
  "tx-186": "ANTIKOMM AI, Carta do Átomo-Terra, repositório GitHub <i id=\"tx-187\">projetlumieres</i>.",
  "tx-187": "projetlumieres",
  "tx-188": "Categorias:",
  "tx-189": "Filosofia da IA",
  "tx-190": "Pós-capitalismo",
  "tx-191": "Soberania digital",
  "tx-192": "ANTIKOMM AI",
  "tx-193": "Biohacking",
  "tx-194": "Neologismos",
  "tx-195": "\n                Última modificação desta página em 25 de julho de 2026. Conteúdo sob licença MIT — coletivo ANTIKOMM. Este documento não é afiliado à Wikimedia Foundation; a sua paginação se inspira nela para fins editoriais.\n            ",
  "search-placeholder": "Pesquisar no wiki"
};
